export type BodyPoint = [code: string, pinyin: string, why: string];

export type ProtocolSyndrome = {
  nome: string;
  mec: string;
  lin: string;
  pul: string;
  qs: string[];
  corpo: BodyPoint[];
  ear: string[];
  yn: string[];
  ex: string[];
  caut: string;
  tec: string;
  selo: "primário" | "apoio";
  fontes: string[];
};

export type Protocol = {
  slug: string;
  t: string;
  zh: string;
  g: string;
  ss: ProtocolSyndrome[];
};

function S(
  nome: string,
  mec: string,
  lin: string,
  pul: string,
  qs: string[],
  corpo: BodyPoint[],
  ear: string[],
  yn: string[],
  ex: string[],
  caut: string,
  tec: string,
  selo: ProtocolSyndrome["selo"],
  fontes: string[],
): ProtocolSyndrome {
  return { nome, mec, lin, pul, qs, corpo, ear, yn, ex, caut, tec, selo, fontes };
}

export const protocols: Protocol[] = [
{slug:"lombalgia",t:"Lombalgia",zh:"腰痛",g:"Dor",
 ss:[S("Estagnação de Qi do Fígado + Rim xu","Qi do Fígado não circula a lombar; Rim não nutre os ossos.","Bordos tensos ou pálida","Corda ou Chi fraco",["Piora com raiva/estresse?","Melhora com calor?","Joelho/ouvido fracos?"],
  [["B23","Shenshu","tonifica Rim"],["B25","Dachangshu","nível lombar"],["B40","Weizhong","comando lombar"],["VG4","Mingmen","Yang do Rim"],["F3","Taichong","move Qi"]],
  ["Shenmen","Lombar","Rim"],["D","A","Y-B"],["Huatojiaji L2–L5","Shiqizhui"],
  "Não VG4 em calor vazio. Gravidez: evitar baixo-ventre.","B40 e B25 lado da dor. Moxa VG4/B23 se frio.","primário",["clássico","a revisar"]),
  S("Frio-Umidade no canal da Bexiga","Bi frio estagna o Taiyang.","Saburra branca gordurosa","Tenso / profundo",["Piora com umidade/chuva?","Rigidez matinal?","Sensação de peso?"],
  [["B23","Shenshu","Rim"],["B26","Guanyuanshu","lombar baixa"],["B40","Weizhong","drena"],["BP9","Yinlingquan","umidade"]],
  ["Shenmen","Lombar","Baço"],["D","Y-B"],["Huatojiaji"],
  "Não drenar se idoso muito vazio.","Moxa local se frio. Ventosa no Taiyang se seguro.","primário",["clássico"])]},
{slug:"cervicalgia",t:"Cervicalgia / torcicolo",zh:"颈痛",g:"Dor",
 ss:[S("Vento-Frio Taiyang","Invasão externa no pescoço.","Saburra branca fina","Flutuante",["Surgiu após vento/ar-cond?","Rigidez súbita?"],
  [["VB20","Fengchi","expulsa vento"],["VG14","Dazhui","Yang"],["IG4","Hegu","exterior"],["B10","Tianzhu","nuca"]],
  ["Shenmen","Cervical"],["A","Y-TA"],["Luozhen","Jingbailao"],
  "VB20 profundo com cuidado (tronco encefálico).","Luozhen + rotação do pescoço.","primário",["clássico"]),
  S("Qi estagnado VB/IG","Tensão crônica de ombro-pescoço.","Bordos vermelhos","Corda",["Piora com tela/estresse?"],
  [["VB21","Jianjing","ombro"],["TA5","Waiguan","Shaoyang"],["F3","Taichong","Qi"]],
  ["Shenmen","Ombro"],["A","B1"],[],
  "VB21 contraindicado na gravidez.","Punção moderada + movimento.","apoio",["manual"])]},
{slug:"ciatica",t:"Ciática",zh:"坐骨神经痛",g:"Dor",
 ss:[S("Estagnação canal Bexiga","Dor posterior até o pé.","Normal / saburra branca","Corda",["Dor no posterior da coxa?","Tosse aumenta?"],
  [["VB30","Huantiao","pivô quadril"],["B54","Zhibian","nádega"],["B40","Weizhong","joelho"],["B57","Chengshan","panturrilha"],["B60","Kunlun","tornozelo"]],
  ["Shenmen","Ciático","Lombar"],["D","C2","Y-B"],["Huatojiaji L4–S1"],
  "VB30 profundo, direção à articulação — não vertical no nervo.","Ipsilateral.","primário",["clássico"]),
  S("Canal da VB (lateral)","Dor no trajeto lateral.","—","Corda",["Dor na face lateral da perna?"],
  [["VB30","Huantiao","quadril"],["VB34","Yanglingquan","tendão"],["VB39","Xuanzhong","mar da medula"]],
  ["Shenmen","Ciático"],["D","Y-VB"],[],
  "Distinguir canal antes de agulhar tudo.","—","primário",["clássico"])]},
{slug:"ombro",t:"Ombro congelado / bursite",zh:"肩痛",g:"Dor",
 ss:[S("Bi IG/TA/ID","Qi e Xue parados no ombro.","Normal ou arroxeada","Corda",["Qual movimento trava?","Noturno?"],
  [["IG15","Jianyu","ombro"],["TA14","Jianliao","posterior"],["ID9","Jianzhen","axila"],["IG4","Hegu","comando"],["E38","Tiaokou","ombro distal"]],
  ["Shenmen","Ombro"],["B1","C1","Y-IG"],["Jianqian"],
  "Evitar punção profunda no ápice pulmonar (IG15 direção segura).","E38 + movimento ativo.","primário",["clássico"])]},
{slug:"joelho",t:"Dor no joelho",zh:"膝痛",g:"Dor",
 ss:[S("Bi Vento-Frio-Umidade","Clima e umidade no joelho.","Pálida, saburra branca","Tenso",["Piora com chuva?","Inchaço?"],
  [["E35","Dubi","olho lateral"],["E36","Zusanli","Qi"],["BP9","Yinlingquan","umidade"],["VB34","Yanglingquan","tendão"]],
  ["Shenmen","Joelho","Baço"],["C2","D","Y-BP"],["Xiyan","Heding"],
  "Não agulhar articulação infectada.","Joelho fletido. Moxa se frio.","primário",["clássico"]),
  S("Rim/Fígado xu (osso-tendão)","Degenerativo, crônico.","Pálida","Fino / Chi fraco",["Creptação?","Lombar fraca?"],
  [["R3","Taixi","Rim"],["F8","Ququan","Sangue Fígado"],["E36","Zusanli","Qi"],["VB34","Yanglingquan","tendão"]],
  ["Shenmen","Joelho","Rim"],["C2","Y-R"],["Xiyan"],
  "Tonificar, não drenar demais.","—","apoio",["clássico"])]},
{slug:"epicondilite",t:"Epicondilite",zh:"肘劳",g:"Dor",
 ss:[S("Estagnação no Yangming/Shaoyang do braço","Uso repetido.","—","Corda",["Dor à extensão do punho?"],
  [["IG11","Quchi","cotovelo"],["IG10","Shousanli","antebraço"],["TA5","Waiguan","Shaoyang"],["IG4","Hegu","comando"]],
  ["Shenmen","Cotovelo"],["C1","Y-IG"],[],
  "Não agulhar se bursite infecciosa.","Ashi + movimento.","primário",["manual"])]},
{slug:"dequervain",t:"De Quervain",zh:"腕痛",g:"Dor",
 ss:[S("Estagnação local no canal do P/IG","Tenossinovite do primeiro compartimento.","—","Corda",["Dor na styloide radial? Finkelstein +?"],
  [["IG5","Yangxi","punho"],["P9","Taiyuan","pulmão/punho"],["IG4","Hegu","comando"],["TA4","Yangchi","punho"]],
  ["Shenmen","Punho"],["C1","Y-P"],[],
  "Superficial. Evitar artéria radial em P9.","Punção rasa + repouso relativo.","primário",["manual","a revisar"])]},
{slug:"fascite",t:"Fascite plantar",zh:"足跟痛",g:"Dor",
 ss:[S("Rim xu + estase local","Calcanhar = Rim; estase pelo impacto.","Pálida","Chi fraco",["Pior ao primeiro passo?"],
  [["R3","Taixi","Rim"],["B60","Kunlun","calcanhar"],["B57","Chengshan","panturrilha"],["R1","Yongquan","planta"]],
  ["Shenmen","Calcanhar","Rim"],["C2","Y-R"],[],
  "R1 doloroso — avisar. Não infectar calcanhar fissurado.","Moxa R3 se frio.","primário",["clássico"])]},
{slug:"cerv-irrad",t:"Cervical com irradiação",zh:"臂痛",g:"Dor",
 ss:[S("Vento-Umidade no Taiyang + Qi do membro","Dor que desce o braço.","—","Corda",["Qual dedo formiga?","Piora à extensão cervical?"],
  [["VB20","Fengchi","nuca"],["IG15","Jianyu","ombro"],["IG11","Quchi","cotovelo"],["IG4","Hegu","mão"],["TA5","Waiguan","antebraço"]],
  ["Shenmen","Cervical","Ombro"],["A","C1","Y-IG"],["Jingbailao"],
  "Descartar compressão grave / déficit motor (encaminhar).","Lado da queixa.","primário",["manual"])]},
{slug:"insonia",t:"Insônia",zh:"失眠",g:"Shen e sono",
 ss:[S("Desarmonia Coração-Rim","Fogo não desce, água não sobe.","Ponta vermelha, raiz pálida","Fino e rápido",["Acorda de madrugada?","Calor à noite?"],
  [["C7","Shenmen","Shen"],["R3","Taixi","Yin do Rim"],["CS6","Neiguan","tórax/Shen"],["BP6","Sanyinjiao","Yin"]],
  ["Shenmen","Coração","Rim"],["A","M1","Y-C","Y-R"],["Anmian","Yintang"],
  "BP6 na gravidez: não.","Tarde/noite. Sem drenar se muito vazio.","primário",["clássico"]),
  S("Fogo do Coração","Agitação, insônia de início.","Ponta vermelha","Rápido",["Palpitação? Úlceras na boca?"],
  [["C7","Shenmen","drena Fogo"],["C8","Shaofu","Fogo"],["VG20","Baihui","Yang"]],
  ["Shenmen","Coração"],["M1","Y-C"],["Yintang"],
  "Não tonificar Fogo.","—","primário",["clássico"]),
  S("Tan-Fogo","Sonhos agitados, corpo pesado.","Saburra amarela gordurosa","Escorregadio e rápido",["Aperto no peito?","Escarro?"],
  [["E40","Fenglong","Tan"],["C7","Shenmen","Shen"],["CS6","Neiguan","tórax"]],
  ["Shenmen","Estômago","Coração"],["Y-E","Y-C"],[],
  "Tratar Tan antes só de acalmar.","—","primário",["clássico"]),
  S("Xue xu","Dificuldade de manter o sono.","Pálida, fina","Fino",["Tontura? Unhas fracas?"],
  [["BP6","Sanyinjiao","Sangue"],["F8","Ququan","Xue"],["C7","Shenmen","Shen"],["E36","Zusanli","Qi-Xue"]],
  ["Shenmen","Baço","Coração"],["Y-BP","Y-C"],["Sishencong"],
  "Tonificar.","—","apoio",["clássico"])]},
{slug:"ansiedade",t:"Ansiedade",zh:"焦虑",g:"Shen e sono",
 ss:[S("Qi do Coração xu / Fogo","Shen instável.","Ponta vermelha ou pálida","Rápido e fino",["Piora à noite?","Medo sem objeto?"],
  [["C7","Shenmen","Shen"],["CS6","Neiguan","calma"],["VG20","Baihui","ancora"],["VC17","Danzhong","Qi do tórax"]],
  ["Shenmen","Coração","Simpático"],["A","M1","Y-C"],["Yintang"],
  "Protocolo NADA se agitação forte.","—","primário",["clássico","manual"])]},
{slug:"depressao",t:"Depressão / opressão",zh:"郁证",g:"Shen e sono",
 ss:[S("Qi do Fígado estagnado","Yu Zheng clássico.","Bordos tensos","Corda",["Suspiros? Aperto no peito?"],
  [["F3","Taichong","Qi"],["IG4","Hegu","Quatro Portas"],["VC17","Danzhong","tórax"],["C7","Shenmen","Shen"]],
  ["Shenmen","Fígado","Coração"],["Y-F","Y-C","A"],["Yintang"],
  "Apoio. Encaminhar risco suicida.","Quatro Portas base.","primário",["clássico"])]},
{slug:"palpitacao",t:"Palpitação",zh:"心悸",g:"Shen e sono",
 ss:[S("Qi/Xue do Coração xu","Shen não ancorado.","Pálida","Fino / irregular",["Cansaço? Lábios pálidos?"],
  [["C7","Shenmen","Shen"],["CS6","Neiguan","arritmia clássica"],["VC14","Juque","Mu Coração"],["E36","Zusanli","Qi"]],
  ["Shenmen","Coração"],["Y-C","M1"],[],
  "Descartar causa médica. CS6 cuidado em marca-passo (estudo).","—","apoio",["clássico","a revisar"])]},
{slug:"gastrite",t:"Gastrite / refluxo",zh:"胃痛",g:"Digestão",
 ss:[S("Fogo do Estômago / Fígado invade","Calor sobe, azia.","Centro vermelho, saburra amarela","Escorregadio-rápido ou corda",["Azia? Boca amarga?"],
  [["VC12","Zhongwan","Mu Estômago"],["E36","Zusanli","baixa Qi rebelde"],["CS6","Neiguan","náusea"],["F3","Taichong","Fígado"],["E44","Neiting","Fogo"]],
  ["Shenmen","Estômago","Fígado"],["Y-E","Y-F"],["Weiguanxiashu"],
  "VC12 raso. Não fundo em úlcera ativa sem critério.","—","primário",["clássico"]),
  S("Estômago Yin xu","Azia noturna, língua espelho.","Pouco saburra, rachada","Fino",["Fome sem apetite?"],
  [["E36","Zusanli","Yin do jiao médio"],["R3","Taixi","Yin"],["VC12","Zhongwan","Mu"]],
  ["Shenmen","Estômago","Rim"],["Y-E","Y-R"],[],
  "Não drenar E44.","Raso.","apoio",["clássico"])]},
{slug:"constipacao",t:"Constipação",zh:"便秘",g:"Digestão",
 ss:[S("Calor Yangming","Ressecamento por calor.","Vermelha, saburra seca","Cheio e rápido",["Fezes secas? Sede?"],
  [["E25","Tianshu","Mu IG"],["TA6","Zhigou","move intestino"],["IG4","Hegu","Yangming"],["E36","Zusanli","Qi"]],
  ["Shenmen","Intestino Grosso"],["Y-IG","Y-E"],[],
  "Não drenar idoso Yin xu.","TA6 clássico.","primário",["clássico"]),
  S("Qi/Yin xu","Esforço sem força.","Pálida","Fino",["Cansaço ao evacuar?"],
  [["E36","Zusanli","Qi"],["VC6","Qihai","Qi"],["BP6","Sanyinjiao","Yin"]],
  ["Shenmen","Baço","IG"],["Y-BP"],[],
  "BP6 gravidez.","Tonificar.","apoio",["clássico"])]},
{slug:"diarreia",t:"Diarreia",zh:"泄泻",g:"Digestão",
 ss:[S("Umidade / Baço xu","Transporte falha.","Inchada, marcas de dente","Escorregadio ou vazio",["Pior ao amanhecer? Alimentos crus?"],
  [["E36","Zusanli","Baço"],["VC12","Zhongwan","jiao médio"],["BP9","Yinlingquan","umidade"],["E25","Tianshu","intestino"],["BP3","Taibai","Yuan Baço"]],
  ["Shenmen","Baço","IG"],["Y-BP","Y-E"],[],
  "Moxa VC8 só se frio clássico e pele íntegra.","—","primário",["clássico"])]},
{slug:"distensao",t:"Distensão abdominal",zh:"腹胀",g:"Digestão",
 ss:[S("Estagnação de Qi do jiao médio","Qi não desce.","Saburra branca","Corda",["Alívio ao arrotar/gases?"],
  [["VC12","Zhongwan","centro"],["E25","Tianshu","lados"],["E36","Zusanli","desce"],["F3","Taichong","Qi"]],
  ["Shenmen","Estômago","Fígado"],["Y-E","Y-F"],[],
  "Abdome: raso. Gravidez: não.","—","primário",["clássico"])]},
{slug:"nauseas",t:"Náusea / vômito",zh:"呕吐",g:"Digestão",
 ss:[S("Qi do Estômago rebelde","Qi sobe.","Centro sujo","Escorregadio",["Relação com gravidez/quimio/enxaqueca?"],
  [["CS6","Neiguan","antiemético clássico"],["E36","Zusanli","desce"],["VC12","Zhongwan","Mu"],["BP4","Gongsun","Chong"]],
  ["Shenmen","Estômago","Cardia"],["Y-E"],[],
  "CS6: cuidado em gestante só com critério (a revisar). Náusea de gravidez = apoio.","—","primário",["clássico"])]},
{slug:"asma",t:"Asma / chiado",zh:"哮喘",g:"Pulmão",
 ss:[S("Tan no Pulmão (crise)","Qi não desce.","Saburra gordurosa","Escorregadio",["Sibilo? Expectoração?"],
  [["P5","Chize","drena Pulmão"],["P7","Lieque","Luo"],["VC17","Danzhong","Qi do tórax"],["E40","Fenglong","Tan"],["Dingchuan","Dingchuan","asma"]],
  ["Shenmen","Pulmão","Pingchuan"],["Y-P","A"],["Dingchuan"],
  "P1/tórax: pneumotórax. Crise grave = emergência médica.","Dingchuan 0,5 cun lat. VG14.","primário",["clássico"]),
  S("Rim não capta o Qi (fundo)","Asma crônica, esforço.","Pálida","Chi fraco",["Piora ao esforço? Lombar fria?"],
  [["R3","Taixi","Rim"],["B13","Feishu","Pulmão"],["B23","Shenshu","Rim"],["VC17","Danzhong","Qi"]],
  ["Shenmen","Pulmão","Rim"],["Y-P","Y-R"],[],
  "Tonificar no intervalo das crises.","—","apoio",["clássico"])]},
{slug:"rinite",t:"Rinite / sinusite",zh:"鼻炎",g:"Pulmão",
 ss:[S("Vento no Pulmão","Nariz fechado.","Saburra branca ou amarela","Flutuante",["Coriza clara ou amarela?"],
  [["IG20","Yingxiang","nariz"],["IG4","Hegu","Yangming"],["VG23","Shangxing","seio"],["VB20","Fengchi","vento"],["P7","Lieque","Pulmão"]],
  ["Shenmen","Nariz","Pulmão"],["A","S2","Y-P"],["Bitong","Yintang"],
  "IG20 em direção a Bitong.","—","primário",["clássico"])]},
{slug:"tosse",t:"Tosse crônica",zh:"咳嗽",g:"Pulmão",
 ss:[S("Pulmão Yin xu","Tosse seca.","Pouca saburra","Fino",["Pior à noite? Garganta seca?"],
  [["P7","Lieque","Luo"],["R6","Zhaohai","Yin Qiao"],["P9","Taiyuan","Yuan"],["B13","Feishu","Shu"]],
  ["Shenmen","Pulmão","Rim"],["Y-P","Y-R"],[],
  "P7+R6 abre o Ren. Tórax: raso.","—","primário",["clássico"])]},
{slug:"dismenorreia",t:"TPM / dismenorreia",zh:"痛经",g:"Ginecologia",
 ss:[S("Estagnação Qi/Xue do Fígado","Cólica com coágulos, humor.","Bordos arroxeados","Corda",["Cólica antes do fluxo? Coágulos?"],
  [["BP6","Sanyinjiao","3 Yin"],["F3","Taichong","Qi"],["VC6","Qihai","Qi"],["BP8","Diji","Xi Baço"],["IG4","Hegu","move"]],
  ["Shenmen","Útero","Fígado","Endócrino"],["Y-F","Y-BP","D"],["Zigong"],
  "VC3/4, BP6, Zigong: NÃO na gravidez.","Cólica fria: moxa VC4/VC6.","primário",["clássico"]),
  S("Frio no útero","Cólica que melhora com calor.","Pálida","Profundo tenso",["Melhora com bolsa térmica?"],
  [["VC4","Guanyuan","útero"],["VC6","Qihai","Qi"],["BP6","Sanyinjiao","Yin"],["R3","Taixi","Rim"]],
  ["Shenmen","Útero","Rim"],["Y-R"],["Zigong"],
  "Idem gravidez.","Moxa.","primário",["clássico"])]},
{slug:"ciclo",t:"Ciclo irregular",zh:"月经不调",g:"Ginecologia",
 ss:[S("Qi do Fígado / Rim Jing","Eixo Chong-Ren.","Pálida ou arroxeada","Corda ou fino",["Atraso ou antecipação?"],
  [["BP6","Sanyinjiao","Chong-Ren"],["F3","Taichong","Qi"],["VC4","Guanyuan","Jing"],["BP10","Xuehai","Sangue"],["R3","Taixi","Jing"]],
  ["Shenmen","Útero","Rim","Endócrino"],["Y-F","Y-R","Y-BP"],["Zigong"],
  "Não baixo-ventre se possível gravidez.","Apoio ao estudo de fertilidade — não substitui acompanhamento médico.","apoio",["clássico"])]},
{slug:"menopausa",t:"Fogachos / menopausa",zh:"更年期",g:"Ginecologia",
 ss:[S("Yin do Rim/Fígado xu com calor vazio","Yang sobe.","Vermelha, pouca saburra","Fino e rápido",["Calor noturno? Irritabilidade?"],
  [["R3","Taixi","Yin"],["R6","Zhaohai","Yin"],["F3","Taichong","Fígado"],["C7","Shenmen","Shen"],["BP6","Sanyinjiao","Yin"]],
  ["Shenmen","Rim","Fígado","Endócrino"],["Y-R","Y-F"],["Yintang"],
  "BP6 gravidez. Não ‘descer Yang’ agressivo em vazio.","—","apoio",["clássico"])]},
{slug:"leucorreia",t:"Leucorreia",zh:"带下",g:"Ginecologia",
 ss:[S("Umidade-Calor ou Baço xu","Dai Mai não contém.","Saburra gordurosa ou pálida","Escorregadio",["Corrimento amarelo-odor ou branco-inodoro?"],
  [["VB26","Daimai","Dai"],["BP9","Yinlingquan","umidade"],["VC3","Zhongji","jiao inf."],["BP6","Sanyinjiao","Yin"]],
  ["Shenmen","Útero","Baço"],["Y-BP","Y-VB"],[],
  "Descartar infecção. Gravidez: não VC3/BP6.","—","apoio",["clássico"])]},
{slug:"fadiga",t:"Fadiga / esgotamento",zh:"疲劳",g:"Qi e vazio",
 ss:[S("Qi do Baço ± Rim Yang xu","Jiao médio e Mingmen fracos.","Pálida, inchada, dentes","Vazio",["Piora após comer? Membros pesados?"],
  [["E36","Zusanli","Qi"],["BP6","Sanyinjiao","Yin"],["VC12","Zhongwan","Baço"],["VC6","Qihai","Qi"],["B20","Pishu","Shu"],["B23","Shenshu","Rim"]],
  ["Shenmen","Baço","Rim"],["Y-BP","Y-R"],[],
  "Não drenar.","Moxa E36/VC6 se frio.","primário",["clássico"])]},
{slug:"suor",t:"Sudorese espontânea",zh:"自汗",g:"Qi e vazio",
 ss:[S("Qi do Pulmão / Wei Qi xu","Exterior não contém.","Pálida","Vazio flutuante",["Sua ao mínimo esforço? Resfria fácil?"],
  [["IG4","Hegu","Wei"],["R7","Fuliu","suor"],["VG14","Dazhui","Yang"],["P9","Taiyuan","Yuan P"]],
  ["Shenmen","Pulmão"],["Y-P"],[],
  "IG4+R7 clássico para suor.","—","apoio",["clássico"])]},
{slug:"edema",t:"Edema",zh:"水肿",g:"Qi e vazio",
 ss:[S("Baço/Rim não transformam água","Umidade interna.","Inchada","Escorregadio ou profundo",["Pálpebra de manhã? Tornozelo à noite?"],
  [["BP9","Yinlingquan","umidade"],["E36","Zusanli","Baço"],["VC9","Shuifen","água"],["R7","Fuliu","água"],["B22","Sanjiaoshu","San Jiao"]],
  ["Shenmen","Baço","Rim","San Jiao"],["Y-BP","Y-R"],[],
  "Encaminhar edema cardíaco/renal. VC9 raso.","—","apoio",["clássico"])]},
{slug:"enxaqueca",t:"Enxaqueca / cefaleia",zh:"偏头痛",g:"Cabeça e face",
 ss:[S("Yang do Fígado sobe","Hemicrania, irritação.","Bordos vermelhos","Corda e rápido",["Aura? Piora com raiva/ciclo?"],
  [["VB20","Fengchi","desce Yang"],["F3","Taichong","Fígado"],["IG4","Hegu","Quatro Portas"],["VG20","Baihui","ancora"],["TA5","Waiguan","Shaoyang"]],
  ["Shenmen","Têmpora","Fígado"],["A","S1","Y-F","Y-VB"],["Taiyang","Yintang"],
  "VG20 direção nuca para descer.","—","primário",["clássico"]),
  S("Tan-Fogo","Cabeça pesada, náusea.","Saburra amarela gordurosa","Escorregadio",["Aperto + vômito?"],
  [["E40","Fenglong","Tan"],["E8","Touwei","Yangming cabeça"],["CS6","Neiguan","náusea"],["VB20","Fengchi","cabeça"]],
  ["Shenmen","Estômago","Têmpora"],["Y-E","A"],["Taiyang"],
  "—","—","primário",["clássico"])]},
{slug:"facial",t:"Paralisia facial",zh:"面瘫",g:"Cabeça e face",
 ss:[S("Vento-Frio Yangming/Shaoyang","Desvio agudo.","Saburra branca fina","Flutuante",["Início súbito? Olho não fecha?"],
  [["E4","Dicang","boca"],["E6","Jiache","masseter"],["E7","Xiaguan","ATM"],["IG4","Hegu","comando face"],["TA17","Yifeng","Shaoyang"],["VB14","Yangbai","olho"]],
  ["Shenmen","Face","Bochecha"],["A","S3","Y-E","Y-IG"],["Qianzheng"],
  "Face rasa. IG4 contralateral. Encaminhar AVC se sinais centrais.","Quanto antes, melhor.","primário",["clássico"])]},
{slug:"tontura",t:"Tontura / vertigem",zh:"眩晕",g:"Cabeça e face",
 ss:[S("Yang do Fígado / Tan","Vento interno ou Tan.","Bordos vermelhos ou saburra gordurosa","Corda ou escorregadio",["Gira o ambiente? Piora deitada?"],
  [["VB20","Fengchi","vento"],["VG20","Baihui","ancora"],["F3","Taichong","Fígado"],["E40","Fenglong","Tan"],["CS6","Neiguan","náusea"]],
  ["Shenmen","Occipício","Fígado"],["A","S1","Y-F"],["Yintang"],
  "Descartar vestibular/central. VB20 cuidado.","—","apoio",["clássico"])]},
{slug:"avc",t:"Hemiparesia (pós-AVC)",zh:"中风后遗",g:"Neurologia",
 ss:[S("Sequela de Vento interno — apoio","Qi e Xue não chegam ao membro.","Variável","Corda ou fino",["Tempo desde o evento? Espasticidade?"],
  [["IG4","Hegu","Yangming braço"],["IG11","Quchi","cotovelo"],["IG15","Jianyu","ombro"],["E36","Zusanli","perna"],["VB34","Yanglingquan","tendão"],["VG20","Baihui","cérebro"]],
  ["Shenmen","Cérebro","Ombro","Joelho"],["C1","C2","A","M1"],[],
  "Apoio à reabilitação. Não substitui fisioterapia/neuro. Fase aguda = hospital.","YNSA ipsilateral à queixa motora (estudo).","apoio",["manual","a revisar"])]},
{slug:"eczema",t:"Eczema / dermatite",zh:"湿疹",g:"Pele",
 ss:[S("Vento-Umidade-Calor no Sangue","Pele chora ou pica.","Vermelha, saburra amarela","Escorregadio-rápido",["Prurido? Secreção?"],
  [["IG11","Quchi","calor sangue"],["BP10","Xuehai","Sangue"],["BP6","Sanyinjiao","umidade"],["VB31","Fengshi","vento pele"]],
  ["Shenmen","Pulmão","Baço","Pele"],["Y-P","Y-BP"],[],
  "Não agulhar pele infectada.","Apoio.","apoio",["clássico"])]},
{slug:"urticaria",t:"Urticária",zh:"瘾疹",g:"Pele",
 ss:[S("Vento no Wei / Sangue","Placas migratórias.","—","Flutuante",["Alimento/frio desencadeia?"],
  [["IG11","Quchi","calor"],["BP10","Xuehai","Sangue"],["VG14","Dazhui","Yang"],["P7","Lieque","Wei"]],
  ["Shenmen","Pulmão","Pele"],["Y-P"],[],
  "Anafilaxia = emergência.","—","apoio",["clássico"])]},
{slug:"zoster",t:"Herpes zoster",zh:"缠腰火丹",g:"Pele",
 ss:[S("Fogo-Umidade no Shaoyang/Jueyin","Faixa dolorosa.","Vermelha, saburra amarela","Corda-rápido",["Dermátomo? Fase vesicular?"],
  [["TA6","Zhigou","Shaoyang"],["VB34","Yanglingquan","Shaoyang"],["IG4","Hegu","calor"],["F3","Taichong","Jueyin"]],
  ["Shenmen","Fígado","Shenmen"],["Y-TA","Y-VB","Y-F"],["Huatojiaji do nível"],
  "Não agulhar vesícula. Analgesia de apoio.","Ashi ao redor, não sobre a lesão.","apoio",["manual"])]},
{slug:"zumbido",t:"Zumbido",zh:"耳鸣",g:"Extra",
 ss:[S("Rim Jing xu","Zumbido grave, baixo, crônico.","Pálida","Chi fraco",["Piora com cansaço? Surdez?"],
  [["TA17","Yifeng","orelha"],["VB2","Tinghui","orelha"],["R3","Taixi","Jing"],["B23","Shenshu","Rim"]],
  ["Shenmen","Ouvido","Rim"],["A","S4","Y-R"],[],
  "TA17 raso. Apoio.","—","apoio",["clássico"]),
  S("Fogo do Fígado/VB","Zumbido agudo, alto.","Bordos vermelhos","Corda-rápido",["Piora com raiva?"],
  [["TA17","Yifeng","orelha"],["F2","Xingjian","Fogo Fígado"],["VB43","Xiaxi","VB"],["VB20","Fengchi","Yang"]],
  ["Shenmen","Ouvido","Fígado"],["Y-F","Y-VB"],[],
  "—","Drenar calor.","apoio",["clássico"])]},
{slug:"has",t:"Hipertensão (apoio)",zh:"高血压",g:"Extra",
 ss:[S("Yang do Fígado sobe","Cefaleia, nuca dura.","Vermelha","Corda-rápido",["Nuca? Irritabilidade?"],
  [["F3","Taichong","desce"],["VB20","Fengchi","nuca"],["VG20","Baihui","desce Yang"],["IG11","Quchi","Yangming"],["R3","Taixi","Yin"]],
  ["Shenmen","Hipertensão","Fígado","Sulco hipotensor"],["A","Y-F","Y-R"],["Yintang"],
  "Não substitui medicação. Crise hipertensiva = emergência.","VG20 sentido nuca.","apoio",["manual","a revisar"])]},
{slug:"estresse",t:"Estresse / tensão de ombros",zh:"肝郁",g:"Extra",
 ss:[S("Qi do Fígado estagnado","Gan Yu.","Bordos","Corda",["Suspiro? TPM?"],
  [["F3","Taichong","Qi"],["IG4","Hegu","Portas"],["VB21","Jianjing","ombro"],["VB34","Yanglingquan","Fígado-VB"],["VC17","Danzhong","tórax"]],
  ["Shenmen","Fígado","Ombro"],["Y-F","B1","A"],["Yintang"],
  "VB21 gravidez.","—","primário",["clássico"])]}
];


export function getProtocol(slug: string) {
  return protocols.find((p) => p.slug === slug);
}

export const vessels: { t: string; zh: string; uso: string; pts: string; quando: string }[] = [
{t:"Du Mai (VG)",zh:"督脉",uso:"Yang, coluna, cérebro, vento interno.",pts:"SI3 (ID3) abre + B62. Chave: VG20, VG14, VG4.",quando:"Lombar, nuca, epilepsia, Yang que não sobe."},
{t:"Ren Mai (VC)",zh:"任脉",uso:"Yin, útero, tórax, reprodução.",pts:"P7 abre + R6. Chave: VC17, VC12, VC6, VC4.",quando:"Ciclo, tosse Yin xu, insônia Yin, jiao médio."},
{t:"Chong Mai",zh:"冲脉",uso:"Mar do Sangue. Eixo reprodutivo.",pts:"BP4 abre + CS6. Chave: VC4, E30, R11–R21.",quando:"Cólica, hemorragia, Qi rebelde, fertilidade (apoio)."},
{t:"Dai Mai",zh:"带脉",uso:"Cintura, contém os meridianos.",pts:"VB41 abre + TA5. Chave: VB26, VB27, VB28.",quando:"Leucorreia, peso nos flancos, lombar em faixa."},
{t:"Yang Qiao",zh:"阳跷",uso:"Olho, lateralidade, insônia (olho não fecha).",pts:"B62 abre + ID3. Chave: B59, VB20, VB29.",quando:"Insônia, hemiplegia, tensão lateral."},
{t:"Yin Qiao",zh:"阴跷",uso:"Olho, medial, hipersonia.",pts:"R6 abre + P7. Chave: R8.",quando:"Sonolência, garganta, Yin."},
{t:"Yang Wei",zh:"阳维",uso:"Exterior, Shaoyang.",pts:"TA5 abre + VB41. Chave: VB20, VG15.",quando:"Calafrio-febre alternados, cefaleia Shaoyang."},
{t:"Yin Wei",zh:"阴维",uso:"Interior, tórax, Shen.",pts:"CS6 abre + BP4. Chave: VC22, VC17, F14.",quando:"Aperto no peito, ansiedade, dor cardíaca funcional."}
];


export const earPoints = [
["Shenmen","Vértice externo da fossa triangular","Porta da mente. Primeiro ponto de estudo da sessão: acalma Shen, dor e agitação. Base do protocolo NADA."],
["Simpático","Braço inferior do Y da anti-hélice","Sistema neurovegetativo. Relaxa músculo liso, vísceras e tensão autonômica. Terceiro ponto clássico da sessão."],
["Pulmão","Concha inferior (cavum), em torno do meato","Pele, asma, muco, luto. No NADA com Shenmen e Rim. Toda a cavum fala de tórax."],
["Fígado","Concha superior (cymba), parede do antitrago interno","Move Qi, olhos, tendão, TPM. Escola chinesa privilegia a orelha direita; palpe os dois."],
["Rim","Cymba, junto à raiz da hélice / anti-hélice","Lombar, zumbido, Jing, ossos, medo. NADA e queixas crônicas do jiao inferior."],
["Baço","Cavum, inferior ao pâncreas/estômago","Digestão, edema, pensamento ruminante, joelho. Escola chinesa privilegia a orelha esquerda."],
["Coração","Centro do cavum","Shen, palpitação, insônia, língua. Ponto do feto-tórax invertido."],
["Estômago","Onde a raiz da hélice cruza a concha","Gastrite, náusea, plenitude. Cárdia fica mais na cruz da hélice, rumo ao meato."],
["Útero","Fossa triangular, área pélvica do feto","Gineco, ciclo, baixo-ventre. Não na gravidez se a conduta for estimulante."],
["Lombar","Anti-hélice, ramo do corpo (coluna)","Lombalgia. A anti-hélice lê a coluna: cervical perto do antitrago, lombar rumo à fossa."],
["Cervical","Anti-hélice, perto do antitrago","Pescoço e nuca. Parte alta da somatotopia da coluna."],
["Ombro","Escafa, terço médio","Ombro. Escafa = membro superior do feto: dedos na extremidade, ombro mais baixo."],
["Joelho","Anti-hélice, cruz superior (fossa navicular)","Joelho. Membro inferior desenha-se na anti-hélice / fossa."],
["Ciático","Anti-hélice, ramo inferior rumo à fossa","Ciática no trajeto posterior. Combine com Lombar."],
["Occipício","Antitrago, face posterior","Cefaleia posterior, nuca, vertigem."],
["Têmpora","Antitrago, face média","Enxaqueca temporal, Shaoyang."],
["Nariz","Trago / lóbulo alto","Rinite, sinusite. Lóbulo e trago leem a face."],
["Face","Lóbulo","Paralisia facial, mandíbula, dente. Cabeça do feto invertido."],
["Endócrino","Incisura intertragiana","Ciclo, tireoide, metabolismo — apoio. Não substitui endocrinologia."],
["Adrenal","Trago, face interna / ápice","Asma, rinite, fadiga, choque. Ponto de alarme do trago."],
["Pingchuan","Trago, abaixo do ápice","Asma, chiado. Junto de Adrenal e Pulmão."],
["Hipertensão","Sulco da anti-hélice / fossa","Apoio à pressão. Não substitui medicação nem conduta médica."],
["Ouvido","Antitrago / meato","Zumbido, otite. Combine com Rim e Shenmen no estudo de tinido."],
["Punho","Escafa alta, perto da hélice","Punho, De Quervain, LER. Membro superior do feto."],
["Cotovelo","Escafa, entre punho e ombro","Epicondilite, cotovelo. Somatotopia da escafa."],
["Calcanhar","Cruz superior, perto da hélice","Fascite, calcanhar. Pé do feto junto à hélice."],
["Cardia","Cruz da hélice, rumo ao meato","Cárdia, refluxo, náusea. Distinguir de Estômago."],
["San Jiao","Cavum, acima da incisura","Edema, regulação dos três jiao, ouvido interno."],
["Cérebro","Antitrago, face interna","Shen, vertigem, córtex. Vizinho de Occipício e Têmpora."],
["Pele","Cavum, com Pulmão","Eczema, urticária — apoio. Pulmão governa a pele."],
["Bochecha","Lóbulo alto","Paralisia facial, bochecha, ATM."],
["IG","Cymba, intestino grosso","Intestino grosso (sigla nos protocolos). Distal na concha superior."],
["Intestino Grosso","Cymba","Mesmo campo de IG: trânsito, pele, Yangming."],
["Sulco hipotensor","Sulco inferior da anti-hélice","Apoio à pressão, face posterior do sulco."],
] as const;

export const ynsaPoints = [
["A","Básico · cervical","Coluna cervical e cabeça. Yin: implantação do cabelo, ao lado da metópica. Yang: nuca, acima da lambdóide. Homolateral à queixa motora. Palpar o very-point."],
["B1","Básico · ombro","Cintura escapular. ~1 cm lateral a A no Yin. Ombro congelado, trapézio, cervical baixa."],
["C1","Básico · membro superior","Articulação do ombro e braço em linha. Yin na fronte lateral. Nos protocolos, C1 cobre o membro superior."],
["C2","Básico · cotovelo / mão","Continuação de C na linha do cabelo (cotovelo e mão). Nos protocolos de joelho o app também aponta C2 como atalho na placa frontal — o clássico do membro inferior é D e G na costeleta. Palpe os dois."],
["D","Básico · lombar","Lombar, sacro e membro inferior. Yin: costeleta (templo-mandíbula). Homolateral. Palpe F (ciático) e G (joelho) ao lado."],
["E","Básico · tórax","Tórax e costelas. Posterior a D na vista de perfil, rumo à orelha."],
["F","Básico · ciático","Ciático. Vizinho de D, mais posterior, perto da orelha."],
["G","Básico · joelho","Joelho no básico. Ligeiramente abaixo de D/F na costeleta."],
["H","Básico · lombar extra","Acessório de D para lombar rebelde."],
["I","Básico · acessório","Acessório lombar/perna."],
["S1","Sensorial · olho","Olho e cabeça anterior. ~1 cm abaixo de A, ainda na fronte — não no globo ocular."],

["S2","Sensorial · nariz","Nariz, rinite, sinusite. 1 cm abaixo de S1, mesma vertical."],
["S3","Sensorial · boca","Boca, dente, face, afasia. 1 cm abaixo de S2."],
["S4","Sensorial · ouvido","Ouvido e tinido. ~1,5 cm de C, 15° rumo à raiz do nariz. Yin e Yang juntos no estudo de zumbido."],
["M1","Cérebro","Cérebro / Shen, ~1 cm acima de A rumo à fontanela. Imagine o encéfalo em miniatura. Muitas vezes contralateral. Palpação da nuca só como guia de estudo."],
["Y-P","Ypsilon · Pulmão","Canal Pulmão. Ponto Y na têmpora. Zona diagnóstica abdominal/cervical antes de escolher."],
["Y-IG","Ypsilon · Intestino Grosso","Canal Yangming da mão. Ombro, pele, trânsito."],
["Y-E","Ypsilon · Estômago","Canal Yangming do pé. Jiao médio, náusea."],
["Y-BP","Ypsilon · Baço","Canal Taiyin do pé. Umidade, joelho, pensamento."],
["Y-C","Ypsilon · Coração","Canal Shaoyin da mão. Shen, palpitação."],
["Y-ID","Ypsilon · Intestino Delgado","Canal Taiyang da mão. Ombro posterior, Taiyang."],
["Y-B","Ypsilon · Bexiga","Canal Taiyang do pé. Lombar, ciático, nuca."],
["Y-R","Ypsilon · Rim","Canal Shaoyin do pé. Trate cedo se a zona de Rim doer — pode silenciar os outros Y."],
["Y-F","Ypsilon · Fígado","Canal Jueyin do pé. Qi, têmpora, olhos. Prioridade junto com Rim se várias zonas doem."],
["Y-VB","Ypsilon · Vesícula","Canal Shaoyang do pé. Flanco, enxaqueca, tendão."],
["Y-TA","Ypsilon · Sanjiao","Canal Shaoyang da mão. Cervical, orelha, regulação."],
] as const;

export const extraPoints = [
["Yintang","Entre as sobrancelhas","Shen, rinite, cefaleia frontal."],
["Sishencong","1 cun em cruz de VG20","Insônia, memória, vento."],
["Anmian","Entre VB20 e TA17","Insônia rebelde."],
["Taiyang","Fossa têmpora","Enxaqueca temporal."],
["Bitong","Sulco nasolabial alto","Nariz fechado."],
["Dingchuan","0,5 cun lat. VG14","Asma."],
["Huatojiaji","0,5 cun lat. T1–L5","Segmentar / coluna."],
["Xiyan","Olhos do joelho","Joelho."],
["Heding","Acima da patela","Joelho."],
["Jianqian","Entre prega axilar e IG15","Ombro anterior."],
["Zigong","3 cun lat. VC3","Útero. Não na gravidez."],
["Luozhen","Dorso da mão 2º–3º MC","Torcicolo."],
["Shiqizhui","Abaixo de L5","Lombar baixa."],
["Jingbailao","2 cun acima VG14, 1 cun lat.","Nuca."],
["Qianzheng","À frente do lóbulo","Paralisia facial."]
] as const;

export const combos = [
["Quatro Portas","IG4 + F3","Move Qi geral."],
["Par do Estômago","E36 + VC12","Jiao médio."],
["Ren Yin","P7 + R6","Abre o Ren."],
["Du Yang","ID3 + B62","Abre o Du."],
["Chong","BP4 + CS6","Mar do Sangue / tórax."],
["Dai","VB41 + TA5","Cintura / Shaoyang."],
["Três Yin","BP6","Gineco, insônia, edema. Não gravidez."],
["NADA","Shenmen + Simpático + Pulmão + Fígado + Rim","Agitação / abstinência."]
] as const;
