#!/usr/bin/env python3
from pathlib import Path
S: dict[str, tuple[str, str, str, str, str]] = {}
def add(code, py, cat, loc, use, caut=""):
    S[code] = (py, cat, loc, use, caut)

add("P1","Zhongfu","Mu do Pulmão","1º espaço intercostal, 6 cun lat. à linha média, abaixo da clavícula.","Tosse, asma, plenitude no peito, ombro.","Tórax: raso — risco de pneumotórax.")
add("P2","Yunmen","—","Abaixo da extremidade acromial da clavícula, 6 cun lat., na depressão.","Tosse, asma, dor no ombro e peito.","Tórax: raso.")
add("P3","Tianfu","—","Face ântero-medial do braço, 3 cun abaixo da prega axilar, no bíceps.","Asma, epistaxe, dor no braço.")
add("P4","Xiabai","—","Face ântero-medial do braço, 4 cun abaixo da prega axilar.","Tosse, dor no peito e no braço.")
add("P5","Chize","He-mar","Prega cubital, no lado radial do tendão do bíceps.","Tosse, asma, calor no Pulmão, cotovelo.")
add("P6","Kongzui","Xi","Palma do antebraço, 7 cun acima da prega do punho, na linha P5–P9.","Tosse aguda, hemoptise, asma.")
add("P7","Lieque","Luo · abre o Ren","1,5 cun acima da prega do punho, na styloide do rádio, na tabaqueira.","Exterior, nuca, tosse, abre o Ren com R6.","Superficial.")
add("P8","Jingqu","Jing-rio","1 cun acima da prega do punho, no lado radial da artéria radial.","Tosse, asma, dor no peito.","Evitar a artéria.")
add("P9","Taiyuan","Yuan · Hui dos vasos","Prega do punho, no lado radial da artéria radial, na depressão.","Tosse, asma, pulso, Yuan do Pulmão.","Evitar a artéria radial.")
add("P10","Yuji","Ying-manancial","Meio do 1º metacarpo, na eminência tenar, na palma.","Calor na garganta, tosse, afonia.")
add("P11","Shaoshang","Jing-poço","0,1 cun proximal ao ângulo radial da unha do polegar.","Dor de garganta, calor, reanimação, sangria.")
add("IG1","Shangyang","Jing-poço","0,1 cun proximal ao ângulo radial da unha do indicador.","Dor de garganta, calor, dente, sangria.")
add("IG2","Erjian","Ying-manancial","Distal à 2ª articulação MCF do indicador, lado radial, punho cerrado.","Dor de dente, garganta, calor.")
add("IG3","Sanjian","Shu-arroio","Proximal à 2ª cabeça do metacarpo, lado radial, punho cerrado.","Olhos, dente, garganta, diarreia.")
add("IG4","Hegu","Yuan","Meio do 2º metacarpo, no lado radial, no ventre do 1º interósseo.","Dor, face, exterior, Quatro Portas com F3.","Não na gravidez.")
add("IG5","Yangxi","Jing-rio","Prega dorsal do punho, entre os tendões de extensor longo e curto do polegar.","Punho, dente, olho, De Quervain.")
add("IG6","Pianli","Luo","3 cun acima de IG5, na linha IG5–IG11.","Ouvido, zumbido, Luo do IG.")
add("IG7","Wenliu","Xi","5 cun acima de IG5, na linha IG5–IG11.","Dor aguda no antebraço, boca, face.")
add("IG8","Xialian","—","4 cun abaixo de IG11, na linha IG5–IG11.","Cotovelo, braço, cabeça.")
add("IG9","Shanglian","—","3 cun abaixo de IG11.","Ombro, braço, hemiparesia.")
add("IG10","Shousanli","—","2 cun abaixo de IG11, no Yangming do braço.","Dor no braço, ombro, dente, hemiparesia.")
add("IG11","Quchi","He-mar","Prega cubital, meio entre o epicôndilo lateral e o tendão do bíceps, cotovelo fletido.","Calor, pele, imunidade, cotovelo.")
add("IG12","Zhouliao","—","1 cun acima de IG11, na borda do úmero.","Cotovelo, braço.")
add("IG13","Shouwuli","—","3 cun acima de IG11, na linha IG11–IG15.","Braço, cotovelo.","Cuidado com o nervo radial.")
add("IG14","Binao","—","Lateral do braço, inserção do deltoide, na linha IG11–IG15.","Ombro, braço, olho.")
add("IG15","Jianyu","—","Depressão ântero-inferior do acrômio, braço em abdução.","Ombro congelado, bursite.","Não fundo rumo ao ápice pulmonar.")
add("IG16","Jugu","—","Depressão entre o acrômio e a espinha da escápula.","Ombro, nuca.")
add("IG17","Tianding","—","Lateral do pescoço, 1 cun abaixo de IG18, no bordo posterior do ECM.","Garganta, voz.","Cuidado com o feixe carotídeo.")
add("IG18","Futu","—","Nível da ponta da laringe, entre as duas cabeças do ECM.","Garganta, tosse, voz.","Cuidado com a carótida.")
add("IG19","Kouheliao","—","Abaixo da borda lateral da narina, 0,5 cun.","Nariz, rinite, paralisia facial.")
add("IG20","Yingxiang","—","No sulco nasolabial, ao lado da asa do nariz.","Nariz, sinusite, paralisia facial.")
add("E1","Chengqi","—","Entre o globo ocular e o infraorbitário, na vertical da pupila.","Olho, lacrimejo.","Raso. Órbita.")
add("E2","Sibai","—","Forame infraorbitário, vertical da pupila.","Olho, face, tic.")
add("E3","Juliao","—","Nível da borda inferior da asa do nariz, vertical da pupila.","Face, dente, sinusite.")
add("E4","Dicang","—","0,4 cun lateral ao ângulo da boca.","Paralisia facial, sialorreia, boca.")
add("E5","Daying","—","Anterior ao ângulo da mandíbula, na pulsação da massetérica.","Mandíbula, dente.","Evitar a artéria.")
add("E6","Jiache","—","Um dedo anterior e superior ao ângulo da mandíbula, no masseter.","ATM, dente, trismo, paralisia facial.")
add("E7","Xiaguan","—","Depressão inferior ao arco zigomático, anterior ao côndilo, boca fechada.","ATM, dente, ouvido.")
add("E8","Touwei","—","Ângulo fronto-temporal, 0,5 cun dentro da implantação do cabelo.","Cefaleia Yangming, tontura.")
add("E9","Renying","—","Nível da cartilagem tireoide, borda anterior do ECM, sobre a carótida.","Garganta, hipertensão (apoio).","Não puncionar a carótida.")
add("E10","Shuitu","—","Borda anterior do ECM, no meio entre E9 e E11.","Garganta, tosse, asma.")
add("E11","Qishe","—","Borda superior da clavícula, entre as duas inserções do ECM.","Garganta, tosse.","Raso — ápice pulmonar.")
add("E12","Quepen","—","Meio da fossa supraclavicular, 4 cun lat.","Tosse, asma.","Raso — pneumotórax.")
add("E13","Qihu","—","Borda inferior da clavícula, 4 cun lat.","Tosse, peito.","Raso.")
add("E14","Kufang","—","1º espaço intercostal, 4 cun lat.","Tosse, peito.","Raso.")
add("E15","Wuyi","—","2º espaço intercostal, 4 cun lat.","Tosse, mama.","Raso.")
add("E16","Yingchuang","—","3º espaço intercostal, 4 cun lat.","Mama, tosse.","Raso.")
add("E17","Ruzhong","—","Centro do mamilo, 4º espaço.","Referência. Não se punciona.")
add("E18","Rugen","—","5º espaço intercostal, 4 cun lat., abaixo do mamilo.","Mama, lactação.","Raso.")
add("E19","Burong","—","6 cun acima do umbigo, 2 cun lat.","Estômago, náusea.","Abdome: raso.")
add("E20","Chengman","—","5 cun acima do umbigo, 2 cun lat.","Estômago, plenitude.")
add("E21","Liangmen","—","4 cun acima do umbigo, 2 cun lat.","Gastrite, dor epigástrica.")
add("E22","Guanmen","—","3 cun acima do umbigo, 2 cun lat.","Estômago, intestino.")
add("E23","Taiyi","—","2 cun acima do umbigo, 2 cun lat.","Estômago, Shen (inquietação).")
add("E24","Huaroumen","—","1 cun acima do umbigo, 2 cun lat.","Intestino, epigástrio.")
add("E25","Tianshu","Mu do IG","2 cun lat. ao umbigo.","Constipação, diarreia, Mu do Intestino Grosso.","Gravidez: não.")
add("E26","Wailing","—","1 cun abaixo do umbigo, 2 cun lat.","Intestino, dismenorreia.")
add("E27","Daju","—","2 cun abaixo do umbigo, 2 cun lat.","Jiao inferior, hérnia, urina.")
add("E28","Shuidao","—","3 cun abaixo do umbigo, 2 cun lat.","Urina, fertilidade (apoio).","Gravidez: não.")
add("E29","Guilai","—","4 cun abaixo do umbigo, 2 cun lat.","Útero, ciclo, hérnia.","Gravidez: não.")
add("E30","Qichong","Chong","5 cun abaixo do umbigo, 2 cun lat., acima da virilha.","Chong Mai, ciclo, hérnia.","Gravidez: não.")
add("E31","Biguan","—","Abaixo da espinha ilíaca ântero-superior, no nível do períneo, na prega.","Quadril, paralisia da perna.")
add("E32","Futu","—","Linha E31–E34, 6 cun acima da borda superior da patela.","Joelho, quadril, paralisia.")
add("E33","Yinshi","—","3 cun acima da borda superior da patela, no vasto lateral.","Joelho.")
add("E34","Liangqiu","Xi","2 cun acima da borda súpero-lateral da patela.","Joelho, dor aguda, Xi do Estômago.")
add("E35","Dubi","—","Olho lateral do joelho, abaixo da patela, tendão patelar lateral.","Joelho. Joelho fletido.")
add("E36","Zusanli","He-mar · mar do Qi","3 cun abaixo de E35, um dedo lateral à crista da tíbia.","Qi, digestão, imunidade, fadiga, joelho.")
add("E37","Shangjuxu","He inferior do IG","3 cun abaixo de E36, um dedo lateral à tíbia.","Intestino grosso, diarreia, apendicite (apoio).")
add("E38","Tiaokou","—","8 cun abaixo de E35 (meio E35–E41).","Ombro distal, perna.")
add("E39","Xiajuxu","He inferior do ID","1 cun abaixo de E37.","Intestino delgado, diarreia.")
add("E40","Fenglong","Luo","8 cun acima do maléolo lat., dois dedos laterais à crista da tíbia (1 cun lat. a E38).","Tan, expectoração, tontura, Luo do Estômago.")
add("E41","Jiexi","Jing-rio","Meio da prega dorsal do tornozelo, entre os tendões do EHL e EDL.","Tornozelo, cabeça, Estômago.")
add("E42","Chongyang","Yuan","Ponto mais alto do dorso do pé, entre 2º e 3º cuneiformes, pulso da dorsal.","Yuan do Estômago, face, pé.","Evitar a artéria.")
add("E43","Xiangu","Shu-arroio","Depressão distal à junção do 2º e 3º metatarsos.","Edema da face, pé.")
add("E44","Neiting","Ying-manancial","Entre o 2º e 3º artelhos, 0,5 cun proximal à membrana.","Fogo do Estômago, dente, face.")
add("E45","Lidui","Jing-poço","0,1 cun proximal ao ângulo lateral da unha do 2º artelho.","Inquietação, face, calor, sangria.")
add("BP1","Yinbai","Jing-poço","0,1 cun proximal ao ângulo medial da unha do hálux.","Sangramento uterino, sono, Jing-poço.")
add("BP2","Dadu","Ying-manancial","Lado medial do hálux, distal à 1ª MTF.","Estômago, Baço, calor.")
add("BP3","Taibai","Yuan · Shu-arroio","Lado medial do pé, proximal e inferior à cabeça do 1º metatarso.","Yuan do Baço, umidade, digestão.")
add("BP4","Gongsun","Luo · abre o Chong","Lado medial, distal e inferior à base do 1º metatarso.","Chong, náusea, gineco, Luo.")
add("BP5","Shangqiu","Jing-rio","Depressão anterior e inferior ao maléolo medial.","Baço, edema, tornozelo.")
add("BP6","Sanyinjiao","Encontro dos 3 Yin","3 cun acima do maléolo medial, borda posterior da tíbia.","Gineco, insônia, edema, Yin.","Não na gravidez.")
add("BP7","Lougu","—","3 cun acima de BP6, borda posterior da tíbia.","Umidade, perna.")
add("BP8","Diji","Xi","3 cun abaixo de BP9, na linha BP9–BP6.","Dismenorreia, Xi do Baço.","Gravidez: critério.")
add("BP9","Yinlingquan","He-mar","Depressão inferior ao côndilo medial da tíbia, joelho fletido.","Umidade, edema, joelho, urina.")
add("BP10","Xuehai","Mar do Sangue","2 cun acima da borda súpero-medial da patela, no vasto medial.","Sangue, pele, prurido, ciclo.")
add("BP11","Jimen","—","6 cun acima do côndilo medial, na linha BP10–BP12.","Urina, virilha.")
add("BP12","Chongmen","—","3,5 cun lat. a VC2, no nível do ramo superior do púbis.","Urina, hérnia.","Evitar a femoral.")
add("BP13","Fushe","—","0,7 cun acima de BP12, 4 cun lat.","Intestino, hérnia.")
add("BP14","Fujie","—","1,3 cun abaixo de BP15, 4 cun lat.","Dor abdominal, diarreia.")
add("BP15","Daheng","—","4 cun lat. ao umbigo.","Intestino, constipação.")
add("BP16","Fuai","—","3 cun acima de BP15, 4 cun lat.","Estômago, intestino.")
add("BP17","Shidou","—","5º espaço intercostal, 6 cun lat.","Costela, plenitude.","Raso.")
add("BP18","Tianxi","—","4º espaço intercostal, 6 cun lat.","Mama, tosse.","Raso.")
add("BP19","Xiongxiang","—","3º espaço intercostal, 6 cun lat.","Peito, costela.","Raso.")
add("BP20","Zhourong","—","2º espaço intercostal, 6 cun lat.","Tosse, plenitude.","Raso.")
add("BP21","Dabao","Luo maior","6º espaço intercostal, na linha médio-axilar.","Flanco, Luo maior do Baço.","Raso.")
add("C1","Jiquan","—","Centro da axila, no lado medial da artéria.","Braço, peito.","Evitar a artéria axilar.")
add("C2","Qingling","—","3 cun acima da prega cubital, no sulco bicipital medial.","Braço, dor no peito.")
add("C3","Shaohai","He-mar","Prega cubital, no lado ulnar, cotovelo fletido.","Shen, cotovelo, calor do Coração.")
add("C4","Lingdao","Jing-rio","1,5 cun acima da prega do punho, no lado radial do flexor ulnar do carpo.","Shen, voz, antebraço.")
add("C5","Tongli","Luo","1 cun acima da prega do punho, radial ao FUC.","Afasia, palpitação, Luo do Coração.")
add("C6","Yinxi","Xi","0,5 cun acima da prega do punho, radial ao FUC.","Suor noturno, palpitação, Xi.")
add("C7","Shenmen","Yuan · Shu-arroio","Prega do punho, no lado radial do tendão do flexor ulnar do carpo.","Shen, insônia, ansiedade, Yuan.")
add("C8","Shaofu","Ying-manancial","Palma, entre 4º e 5º metacarpos, no ponto em que o 5º dedo toca a palma.","Fogo do Coração, úlcera na boca, palpitação.")
add("C9","Shaochong","Jing-poço","0,1 cun proximal ao ângulo radial da unha do 5º dedo.","Reanimação, calor, Shen, sangria.")
add("ID1","Shaoze","Jing-poço","0,1 cun proximal ao ângulo ulnar da unha do 5º dedo.","Lactação, olho, calor, sangria.")
add("ID2","Qiangu","Ying-manancial","Distal à 5ª MCF, lado ulnar, punho cerrado.","Olho, ouvido, dente.")
add("ID3","Houxi","Shu-arroio · abre o Du","Proximal à 5ª MCF, lado ulnar, no fim da prega palmar, punho cerrado.","Abre o Du, nuca, coluna, insônia (olho).")
add("ID4","Wangu","Yuan","Entre a base do 5º metacarpo e o triquetral, lado ulnar.","Yuan do ID, punho, dente.")
add("ID5","Yanggu","Jing-rio","Depressão entre o estiloide ulnar e o triquetral.","Punho, ouvido, dente.")
add("ID6","Yanglao","Xi","Dorso do punho, na depressão radial à cabeça da ulna, palma no peito.","Xi, ombro, lombar, vista (idoso).")
add("ID7","Zhizheng","Luo","5 cun acima do punho, na linha ID5–ID8.","Luo, nuca, dedos.")
add("ID8","Xiaohai","He-mar","Sulco entre o olécrano e o epicôndilo medial, cotovelo fletido.","Cotovelo, nervo ulnar, ID.")
add("ID9","Jianzhen","—","1 cun acima da extremidade posterior da prega axilar.","Ombro posterior.")
add("ID10","Naoshu","—","Diretamente acima de ID9, na extremidade inferior da espinha da escápula.","Ombro, escápula.")
add("ID11","Tianzong","—","Fossa infraespinhal, no terço médio da linha da espinha ao ângulo inferior.","Ombro, mama, asma.")
add("ID12","Bingfeng","—","Centro da fossa supraespinhal, acima de ID11.","Ombro.","Raso no ápice.")
add("ID13","Quyuan","—","Extremidade medial da fossa supraespinhal.","Ombro, escápula.")
add("ID14","Jianwaishu","—","3 cun lat. a VG13 (T1), no bordo da escápula.","Ombro, nuca.")
add("ID15","Jianzhongshu","—","2 cun lat. a VG14 (C7).","Nuca, ombro, tosse.")
add("ID16","Tianchuang","—","Borda posterior do ECM, posterior a IG18, no nível da laringe.","Ouvido, garganta.")
add("ID17","Tianrong","—","Posterior ao ângulo da mandíbula, no bordo anterior do ECM.","Garganta, ouvido.")
add("ID18","Quanliao","—","Diretamente abaixo do canto externo do olho, no bordo inferior do zigoma.","Face, dente, paralisia.")
add("ID19","Tinggong","—","Entre o trago e a ATM, com a boca aberta.","Ouvido, zumbido, ATM.")
