/** Fichas didáticas originais (paráfrase). Não reproduz texto de livro. */
export type PointSpec = { py: string; cat: string; loc: string; use: string; caut?: string };

export const POINT_SPECS: Record<string, PointSpec> = {
  B1: { py: "Jingming", cat: "—", loc: "0,1 cun medial e superior ao canto interno do olho.", use: "Olho.", caut: "Órbita: raso, sem retroversão." },
  B2: { py: "Zanzhu", cat: "—", loc: "Extremidade medial da sobrancelha, no supraorbitário.", use: "Olho, cefaleia frontal, sinusite." },
  B3: { py: "Meichong", cat: "—", loc: "Diretamente acima de B2, 0,5 cun dentro do cabelo.", use: "Cefaleia, olho, nariz." },
  B4: { py: "Quchai", cat: "—", loc: "1,5 cun lat. a VG24, 0,5 cun dentro do cabelo.", use: "Cefaleia, olho, nariz." },
  B5: { py: "Wuchu", cat: "—", loc: "0,5 cun posterior a B4.", use: "Cefaleia, epilepsia (apoio)." },
  B6: { py: "Chengguang", cat: "—", loc: "1,5 cun posterior a B5.", use: "Cefaleia, vista." },
  B7: { py: "Tongtian", cat: "—", loc: "1,5 cun posterior a B6.", use: "Nariz, vértice." },
  B8: { py: "Luoque", cat: "—", loc: "1,5 cun posterior a B7.", use: "Tontura, vista." },
  B9: { py: "Yuzhen", cat: "—", loc: "1,3 cun lat. a VG17, na borda superior da protuberância occipital.", use: "Nuca, olho." },
  B10: { py: "Tianzhu", cat: "—", loc: "1,3 cun lat. a VG15, na inserção do trapézio, linha capilar posterior.", use: "Nuca, cefaleia, olho." },
  B11: { py: "Dazhu", cat: "Hui dos ossos", loc: "1,5 cun lat. ao processo espinhoso de T1.", use: "Ossos, articulações, vento." },
  B12: { py: "Fengmen", cat: "—", loc: "1,5 cun lat. ao processo espinhoso de T2.", use: "Vento, resfriado, asma." },
  B13: { py: "Feishu", cat: "Shu do Pulmão", loc: "1,5 cun lat. ao processo espinhoso de T3.", use: "Tosse, asma, pele." },
  B14: { py: "Jueyinshu", cat: "Shu do Pericárdio", loc: "1,5 cun lat. ao processo espinhoso de T4.", use: "Peito, palpitação." },
  B15: { py: "Xinshu", cat: "Shu do Coração", loc: "1,5 cun lat. ao processo espinhoso de T5.", use: "Shen, palpitação, insônia." },
  B16: { py: "Dushu", cat: "Shu do Du", loc: "1,5 cun lat. ao processo espinhoso de T6.", use: "Peito, Qi rebelde." },
  B17: { py: "Geshu", cat: "Hui do Sangue", loc: "1,5 cun lat. ao processo espinhoso de T7.", use: "Sangue, diafragma, pele." },
  B18: { py: "Ganshu", cat: "Shu do Fígado", loc: "1,5 cun lat. ao processo espinhoso de T9.", use: "Fígado, olhos, tendão." },
  B19: { py: "Danshu", cat: "Shu da VB", loc: "1,5 cun lat. ao processo espinhoso de T10.", use: "VB, flanco, amargor." },
  B20: { py: "Pishu", cat: "Shu do Baço", loc: "1,5 cun lat. ao processo espinhoso de T11.", use: "Baço, umidade, digestão." },
  B21: { py: "Weishu", cat: "Shu do Estômago", loc: "1,5 cun lat. ao processo espinhoso de T12.", use: "Estômago, náusea." },
  B22: { py: "Sanjiaoshu", cat: "Shu do San Jiao", loc: "1,5 cun lat. ao processo espinhoso de L1.", use: "Água, edema, San Jiao." },
  B23: { py: "Shenshu", cat: "Shu do Rim", loc: "1,5 cun lat. ao processo espinhoso de L2.", use: "Rim, lombar, Jing, ouvido." },
  B24: { py: "Qihaishu", cat: "—", loc: "1,5 cun lat. ao processo espinhoso de L3.", use: "Qi do jiao inferior, lombar." },
  B25: { py: "Dachangshu", cat: "Shu do IG", loc: "1,5 cun lat. ao processo espinhoso de L4.", use: "Lombar, intestino grosso." },
  B26: { py: "Guanyuanshu", cat: "—", loc: "1,5 cun lat. ao processo espinhoso de L5.", use: "Lombar baixa, jiao inferior." },
  B27: { py: "Xiaochangshu", cat: "Shu do ID", loc: "1,5 cun lat. ao processo espinhoso de S1.", use: "Intestino delgado, urina." },
  B28: { py: "Pangguangshu", cat: "Shu da Bexiga", loc: "1,5 cun lat. ao processo espinhoso de S2.", use: "Bexiga, urina." },
  B29: { py: "Zhonglushu", cat: "—", loc: "1,5 cun lat. ao processo espinhoso de S3.", use: "Lombar, hérnia." },
  B30: { py: "Baihuanshu", cat: "—", loc: "1,5 cun lat. ao processo espinhoso de S4.", use: "Lombar, ânus, leucorreia." },
  B31: { py: "Shangliao", cat: "—", loc: "1º forame sacral, no meio entre o ânus-posterior e a crista.", use: "Gineco, lombar, urina.", caut: "Gravidez: não." },
  B32: { py: "Ciliao", cat: "—", loc: "2º forame sacral.", use: "Dismenorreia, lombar, urina.", caut: "Gravidez: não." },
  B33: { py: "Zhongliao", cat: "—", loc: "3º forame sacral.", use: "Gineco, intestino.", caut: "Gravidez: não." },
  B34: { py: "Xialiao", cat: "—", loc: "4º forame sacral.", use: "Intestino, urina.", caut: "Gravidez: não." },
  B35: { py: "Huiyang", cat: "—", loc: "0,5 cun lat. ao cóccix.", use: "Ânus, hemorroida, leucorreia." },
  B36: { py: "Chengfu", cat: "—", loc: "Meio da prega glútea.", use: "Ciático, nádega." },
  B37: { py: "Yinmen", cat: "—", loc: "6 cun abaixo de B36, na linha B36–B40.", use: "Ciático, posterior da coxa." },
  B38: { py: "Fuxi", cat: "—", loc: "1 cun acima de B39, no lado medial do tendão do bíceps femoral.", use: "Joelho posterior." },
  B39: { py: "Weiyang", cat: "He inferior do San Jiao", loc: "Lado lateral da prega poplítea, medial ao bíceps femoral.", use: "Urina, edema, San Jiao." },
  B40: { py: "Weizhong", cat: "He-mar · comando lombar", loc: "Meio da prega poplítea.", use: "Lombar, ciático, calor no Sangue, pele." },
  B41: { py: "Fufen", cat: "—", loc: "3 cun lat. ao processo espinhoso de T2.", use: "Ombro, vento." },
  B42: { py: "Pohu", cat: "—", loc: "3 cun lat. ao processo espinhoso de T3.", use: "Pulmão, tristeza, tosse." },
  B43: { py: "Gaohuang", cat: "—", loc: "3 cun lat. ao processo espinhoso de T4.", use: "Doença crônica, deficiência, tosse." },
  B44: { py: "Shentang", cat: "—", loc: "3 cun lat. ao processo espinhoso de T5.", use: "Shen, peito." },
  B45: { py: "Yixi", cat: "—", loc: "3 cun lat. ao processo espinhoso de T6.", use: "Peito, asma." },
  B46: { py: "Geguan", cat: "—", loc: "3 cun lat. ao processo espinhoso de T7.", use: "Diafragma, vômito." },
  B47: { py: "Hunmen", cat: "—", loc: "3 cun lat. ao processo espinhoso de T9.", use: "Hun, Fígado, flanco." },
  B48: { py: "Yanggang", cat: "—", loc: "3 cun lat. ao processo espinhoso de T10.", use: "VB, digestão." },
  B49: { py: "Yishe", cat: "—", loc: "3 cun lat. ao processo espinhoso de T11.", use: "Yi, Baço, pensamento." },
  B50: { py: "Weicang", cat: "—", loc: "3 cun lat. ao processo espinhoso de T12.", use: "Estômago." },
  B51: { py: "Huangmen", cat: "—", loc: "3 cun lat. ao processo espinhoso de L1.", use: "Jiao inferior." },
  B52: { py: "Zhishi", cat: "—", loc: "3 cun lat. ao processo espinhoso de L2.", use: "Jing, vontade, lombar, urina." },
  B53: { py: "Baohuang", cat: "—", loc: "3 cun lat. ao 2º forame sacral.", use: "Urina, lombar." },
  B54: { py: "Zhibian", cat: "—", loc: "3 cun lat. ao 4º forame sacral (hiato).", use: "Ciático, nádega, urina." },
  B55: { py: "Heyang", cat: "—", loc: "2 cun abaixo de B40, entre as duas cabeças do gastrocnêmio.", use: "Lombar, útero." },
  B56: { py: "Chengjin", cat: "—", loc: "Meio da panturrilha, 5 cun abaixo de B40, no ventre do gastrocnêmio.", use: "Panturrilha, hemorroida." },
  B57: { py: "Chengshan", cat: "—", loc: "8 cun abaixo de B40, no ventre inferior do gastrocnêmio (V invertido).", use: "Panturrilha, hemorroida, fascite." },
  B58: { py: "Feiyang", cat: "Luo", loc: "7 cun acima de B60, 1 cun lat. e inf. a B57.", use: "Luo da Bexiga, nuca, hemorroida." },
  B59: { py: "Fuyang", cat: "Xi do Yang Qiao", loc: "3 cun acima de B60.", use: "Yang Qiao, tornozelo, cefaleia." },
  B60: { py: "Kunlun", cat: "Jing-rio", loc: "Depressão entre o maléolo lateral e o tendão de Aquiles.", use: "Nuca, lombar, tornozelo, parto.", caut: "Não na gravidez." },
  B61: { py: "Pucan", cat: "—", loc: "Posterior e inferior ao maléolo lateral, no calcâneo, 1,5 cun abaixo de B60.", use: "Calcanhar, Yang Qiao." },
  B62: { py: "Shenmai", cat: "Abre o Yang Qiao", loc: "Diretamente abaixo do maléolo lateral, na depressão.", use: "Yang Qiao, insônia (olho), hemiparesia, nuca." },
  B63: { py: "Jinmen", cat: "Xi", loc: "Anterior e inferior a B62, distal ao cuboide.", use: "Xi da Bexiga, epilepsia (apoio), tornozelo." },
  B64: { py: "Jinggu", cat: "Yuan", loc: "Abaixo da tuberosidade do 5º metatarso, na junção pele vermelha/branca.", use: "Yuan da Bexiga, cabeça, pescoço." },
  B65: { py: "Shugu", cat: "Shu-arroio", loc: "Posterior à cabeça do 5º metatarso, lado lateral.", use: "Cabeça, nuca." },
  B66: { py: "Zutonggu", cat: "Ying-manancial", loc: "Anterior à 5ª MTF, lado lateral.", use: "Cabeça, nuca, digestão." },
  B67: { py: "Zhiyin", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo lateral da unha do 5º artelho.", use: "Parto, apresentação (moxa), olho.", caut: "Não na gravidez (exceto virar feto com moxa sob critério)." },
  BP1: { py: "Yinbai", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo medial da unha do hálux.", use: "Sangramento uterino, sono, Jing-poço." },
  BP2: { py: "Dadu", cat: "Ying-manancial", loc: "Lado medial do hálux, distal à 1ª MTF.", use: "Estômago, Baço, calor." },
  BP3: { py: "Taibai", cat: "Yuan · Shu-arroio", loc: "Lado medial do pé, proximal e inferior à cabeça do 1º metatarso.", use: "Yuan do Baço, umidade, digestão." },
  BP4: { py: "Gongsun", cat: "Luo · abre o Chong", loc: "Lado medial, distal e inferior à base do 1º metatarso.", use: "Chong, náusea, gineco, Luo." },
  BP5: { py: "Shangqiu", cat: "Jing-rio", loc: "Depressão anterior e inferior ao maléolo medial.", use: "Baço, edema, tornozelo." },
  BP6: { py: "Sanyinjiao", cat: "Encontro dos 3 Yin", loc: "3 cun acima do maléolo medial, borda posterior da tíbia.", use: "Gineco, insônia, edema, Yin.", caut: "Não na gravidez." },
  BP7: { py: "Lougu", cat: "—", loc: "3 cun acima de BP6, borda posterior da tíbia.", use: "Umidade, perna." },
  BP8: { py: "Diji", cat: "Xi", loc: "3 cun abaixo de BP9, na linha BP9–BP6.", use: "Dismenorreia, Xi do Baço.", caut: "Gravidez: critério." },
  BP9: { py: "Yinlingquan", cat: "He-mar", loc: "Depressão inferior ao côndilo medial da tíbia, joelho fletido.", use: "Umidade, edema, joelho, urina." },
  BP10: { py: "Xuehai", cat: "Mar do Sangue", loc: "2 cun acima da borda súpero-medial da patela, no vasto medial.", use: "Sangue, pele, prurido, ciclo." },
  BP11: { py: "Jimen", cat: "—", loc: "6 cun acima do côndilo medial, na linha BP10–BP12.", use: "Urina, virilha." },
  BP12: { py: "Chongmen", cat: "—", loc: "3,5 cun lat. a VC2, no nível do ramo superior do púbis.", use: "Urina, hérnia.", caut: "Evitar a femoral." },
  BP13: { py: "Fushe", cat: "—", loc: "0,7 cun acima de BP12, 4 cun lat.", use: "Intestino, hérnia." },
  BP14: { py: "Fujie", cat: "—", loc: "1,3 cun abaixo de BP15, 4 cun lat.", use: "Dor abdominal, diarreia." },
  BP15: { py: "Daheng", cat: "—", loc: "4 cun lat. ao umbigo.", use: "Intestino, constipação." },
  BP16: { py: "Fuai", cat: "—", loc: "3 cun acima de BP15, 4 cun lat.", use: "Estômago, intestino." },
  BP17: { py: "Shidou", cat: "—", loc: "5º espaço intercostal, 6 cun lat.", use: "Costela, plenitude.", caut: "Raso." },
  BP18: { py: "Tianxi", cat: "—", loc: "4º espaço intercostal, 6 cun lat.", use: "Mama, tosse.", caut: "Raso." },
  BP19: { py: "Xiongxiang", cat: "—", loc: "3º espaço intercostal, 6 cun lat.", use: "Peito, costela.", caut: "Raso." },
  BP20: { py: "Zhourong", cat: "—", loc: "2º espaço intercostal, 6 cun lat.", use: "Tosse, plenitude.", caut: "Raso." },
  BP21: { py: "Dabao", cat: "Luo maior", loc: "6º espaço intercostal, na linha médio-axilar.", use: "Flanco, Luo maior do Baço.", caut: "Raso." },
  C1: { py: "Jiquan", cat: "—", loc: "Centro da axila, no lado medial da artéria.", use: "Braço, peito.", caut: "Evitar a artéria axilar." },
  C2: { py: "Qingling", cat: "—", loc: "3 cun acima da prega cubital, no sulco bicipital medial.", use: "Braço, dor no peito." },
  C3: { py: "Shaohai", cat: "He-mar", loc: "Prega cubital, no lado ulnar, cotovelo fletido.", use: "Shen, cotovelo, calor do Coração." },
  C4: { py: "Lingdao", cat: "Jing-rio", loc: "1,5 cun acima da prega do punho, no lado radial do flexor ulnar do carpo.", use: "Shen, voz, antebraço." },
  C5: { py: "Tongli", cat: "Luo", loc: "1 cun acima da prega do punho, radial ao FUC.", use: "Afasia, palpitação, Luo do Coração." },
  C6: { py: "Yinxi", cat: "Xi", loc: "0,5 cun acima da prega do punho, radial ao FUC.", use: "Suor noturno, palpitação, Xi." },
  C7: { py: "Shenmen", cat: "Yuan · Shu-arroio", loc: "Prega do punho, no lado radial do tendão do flexor ulnar do carpo.", use: "Shen, insônia, ansiedade, Yuan." },
  C8: { py: "Shaofu", cat: "Ying-manancial", loc: "Palma, entre 4º e 5º metacarpos, no ponto em que o 5º dedo toca a palma.", use: "Fogo do Coração, úlcera na boca, palpitação." },
  C9: { py: "Shaochong", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo radial da unha do 5º dedo.", use: "Reanimação, calor, Shen, sangria." },
  CS1: { py: "Tianchi", cat: "—", loc: "4º espaço intercostal, 1 cun lat. ao mamilo (5 cun lat. à linha média).", use: "Peito, mama.", caut: "Raso. Mama." },
  CS2: { py: "Tianquan", cat: "—", loc: "2 cun abaixo da prega axilar, entre as duas cabeças do bíceps.", use: "Peito, braço." },
  CS3: { py: "Quze", cat: "He-mar", loc: "Prega cubital, no lado ulnar do tendão do bíceps.", use: "Calor no Sangue, vômito, palpitação." },
  CS4: { py: "Ximen", cat: "Xi", loc: "5 cun acima da prega do punho, na linha CS3–CS7.", use: "Xi, dor no peito, palpitação." },
  CS5: { py: "Jianshi", cat: "Jing-rio", loc: "3 cun acima da prega do punho, entre palmar longo e flexor radial.", use: "Shen, náusea." },
  CS6: { py: "Neiguan", cat: "Luo · abre o Yin Wei", loc: "2 cun acima da prega do punho, entre os dois tendões.", use: "Náusea, peito, palpitação, Shen, Yin Wei.", caut: "Cuidado em marca-passo (estudo)." },
  CS7: { py: "Daling", cat: "Yuan · Shu-arroio", loc: "Meio da prega do punho, entre palmar longo e flexor radial.", use: "Yuan, calor no Pericárdio, palma." },
  CS8: { py: "Laogong", cat: "Ying-manancial", loc: "Palma, entre 2º e 3º metacarpos, onde o 3º dedo toca a palma.", use: "Calor, boca, Shen." },
  CS9: { py: "Zhongchong", cat: "Jing-poço", loc: "Centro da ponta do 3º dedo (ou 0,1 cun radial à unha).", use: "Reanimação, calor, sangria." },
  E1: { py: "Chengqi", cat: "—", loc: "Entre o globo ocular e o infraorbitário, na vertical da pupila.", use: "Olho, lacrimejo.", caut: "Raso. Órbita." },
  E2: { py: "Sibai", cat: "—", loc: "Forame infraorbitário, vertical da pupila.", use: "Olho, face, tic." },
  E3: { py: "Juliao", cat: "—", loc: "Nível da borda inferior da asa do nariz, vertical da pupila.", use: "Face, dente, sinusite." },
  E4: { py: "Dicang", cat: "—", loc: "0,4 cun lateral ao ângulo da boca.", use: "Paralisia facial, sialorreia, boca." },
  E5: { py: "Daying", cat: "—", loc: "Anterior ao ângulo da mandíbula, na pulsação da massetérica.", use: "Mandíbula, dente.", caut: "Evitar a artéria." },
  E6: { py: "Jiache", cat: "—", loc: "Um dedo anterior e superior ao ângulo da mandíbula, no masseter.", use: "ATM, dente, trismo, paralisia facial." },
  E7: { py: "Xiaguan", cat: "—", loc: "Depressão inferior ao arco zigomático, anterior ao côndilo, boca fechada.", use: "ATM, dente, ouvido." },
  E8: { py: "Touwei", cat: "—", loc: "Ângulo fronto-temporal, 0,5 cun dentro da implantação do cabelo.", use: "Cefaleia Yangming, tontura." },
  E9: { py: "Renying", cat: "—", loc: "Nível da cartilagem tireoide, borda anterior do ECM, sobre a carótida.", use: "Garganta, hipertensão (apoio).", caut: "Não puncionar a carótida." },
  E10: { py: "Shuitu", cat: "—", loc: "Borda anterior do ECM, no meio entre E9 e E11.", use: "Garganta, tosse, asma." },
  E11: { py: "Qishe", cat: "—", loc: "Borda superior da clavícula, entre as duas inserções do ECM.", use: "Garganta, tosse.", caut: "Raso — ápice pulmonar." },
  E12: { py: "Quepen", cat: "—", loc: "Meio da fossa supraclavicular, 4 cun lat.", use: "Tosse, asma.", caut: "Raso — pneumotórax." },
  E13: { py: "Qihu", cat: "—", loc: "Borda inferior da clavícula, 4 cun lat.", use: "Tosse, peito.", caut: "Raso." },
  E14: { py: "Kufang", cat: "—", loc: "1º espaço intercostal, 4 cun lat.", use: "Tosse, peito.", caut: "Raso." },
  E15: { py: "Wuyi", cat: "—", loc: "2º espaço intercostal, 4 cun lat.", use: "Tosse, mama.", caut: "Raso." },
  E16: { py: "Yingchuang", cat: "—", loc: "3º espaço intercostal, 4 cun lat.", use: "Mama, tosse.", caut: "Raso." },
  E17: { py: "Ruzhong", cat: "—", loc: "Centro do mamilo, 4º espaço.", use: "Referência. Não se punciona." },
  E18: { py: "Rugen", cat: "—", loc: "5º espaço intercostal, 4 cun lat., abaixo do mamilo.", use: "Mama, lactação.", caut: "Raso." },
  E19: { py: "Burong", cat: "—", loc: "6 cun acima do umbigo, 2 cun lat.", use: "Estômago, náusea.", caut: "Abdome: raso." },
  E20: { py: "Chengman", cat: "—", loc: "5 cun acima do umbigo, 2 cun lat.", use: "Estômago, plenitude." },
  E21: { py: "Liangmen", cat: "—", loc: "4 cun acima do umbigo, 2 cun lat.", use: "Gastrite, dor epigástrica." },
  E22: { py: "Guanmen", cat: "—", loc: "3 cun acima do umbigo, 2 cun lat.", use: "Estômago, intestino." },
  E23: { py: "Taiyi", cat: "—", loc: "2 cun acima do umbigo, 2 cun lat.", use: "Estômago, Shen (inquietação)." },
  E24: { py: "Huaroumen", cat: "—", loc: "1 cun acima do umbigo, 2 cun lat.", use: "Intestino, epigástrio." },
  E25: { py: "Tianshu", cat: "Mu do IG", loc: "2 cun lat. ao umbigo.", use: "Constipação, diarreia, Mu do Intestino Grosso.", caut: "Gravidez: não." },
  E26: { py: "Wailing", cat: "—", loc: "1 cun abaixo do umbigo, 2 cun lat.", use: "Intestino, dismenorreia." },
  E27: { py: "Daju", cat: "—", loc: "2 cun abaixo do umbigo, 2 cun lat.", use: "Jiao inferior, hérnia, urina." },
  E28: { py: "Shuidao", cat: "—", loc: "3 cun abaixo do umbigo, 2 cun lat.", use: "Urina, fertilidade (apoio).", caut: "Gravidez: não." },
  E29: { py: "Guilai", cat: "—", loc: "4 cun abaixo do umbigo, 2 cun lat.", use: "Útero, ciclo, hérnia.", caut: "Gravidez: não." },
  E30: { py: "Qichong", cat: "Chong", loc: "5 cun abaixo do umbigo, 2 cun lat., acima da virilha.", use: "Chong Mai, ciclo, hérnia.", caut: "Gravidez: não." },
  E31: { py: "Biguan", cat: "—", loc: "Abaixo da espinha ilíaca ântero-superior, no nível do períneo, na prega.", use: "Quadril, paralisia da perna." },
  E32: { py: "Futu", cat: "—", loc: "Linha E31–E34, 6 cun acima da borda superior da patela.", use: "Joelho, quadril, paralisia." },
  E33: { py: "Yinshi", cat: "—", loc: "3 cun acima da borda superior da patela, no vasto lateral.", use: "Joelho." },
  E34: { py: "Liangqiu", cat: "Xi", loc: "2 cun acima da borda súpero-lateral da patela.", use: "Joelho, dor aguda, Xi do Estômago." },
  E35: { py: "Dubi", cat: "—", loc: "Olho lateral do joelho, abaixo da patela, tendão patelar lateral.", use: "Joelho. Joelho fletido." },
  E36: { py: "Zusanli", cat: "He-mar · mar do Qi", loc: "3 cun abaixo de E35, um dedo lateral à crista da tíbia.", use: "Qi, digestão, imunidade, fadiga, joelho." },
  E37: { py: "Shangjuxu", cat: "He inferior do IG", loc: "3 cun abaixo de E36, um dedo lateral à tíbia.", use: "Intestino grosso, diarreia, apendicite (apoio)." },
  E38: { py: "Tiaokou", cat: "—", loc: "8 cun abaixo de E35 (meio E35–E41).", use: "Ombro distal, perna." },
  E39: { py: "Xiajuxu", cat: "He inferior do ID", loc: "1 cun abaixo de E37.", use: "Intestino delgado, diarreia." },
  E40: { py: "Fenglong", cat: "Luo", loc: "8 cun acima do maléolo lat., dois dedos laterais à crista da tíbia (1 cun lat. a E38).", use: "Tan, expectoração, tontura, Luo do Estômago." },
  E41: { py: "Jiexi", cat: "Jing-rio", loc: "Meio da prega dorsal do tornozelo, entre os tendões do EHL e EDL.", use: "Tornozelo, cabeça, Estômago." },
  E42: { py: "Chongyang", cat: "Yuan", loc: "Ponto mais alto do dorso do pé, entre 2º e 3º cuneiformes, pulso da dorsal.", use: "Yuan do Estômago, face, pé.", caut: "Evitar a artéria." },
  E43: { py: "Xiangu", cat: "Shu-arroio", loc: "Depressão distal à junção do 2º e 3º metatarsos.", use: "Edema da face, pé." },
  E44: { py: "Neiting", cat: "Ying-manancial", loc: "Entre o 2º e 3º artelhos, 0,5 cun proximal à membrana.", use: "Fogo do Estômago, dente, face." },
  E45: { py: "Lidui", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo lateral da unha do 2º artelho.", use: "Inquietação, face, calor, sangria." },
  F1: { py: "Dadun", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo lateral da unha do hálux.", use: "Hérnia, ciclo, Jing-poço." },
  F2: { py: "Xingjian", cat: "Ying-manancial", loc: "Entre hálux e 2º artelho, 0,5 cun proximal à membrana.", use: "Fogo do Fígado, olhos, dismenorreia." },
  F3: { py: "Taichong", cat: "Yuan · Shu-arroio", loc: "Depressão distal à junção do 1º e 2º metatarsos.", use: "Qi do Fígado, Quatro Portas, cefaleia, TPM." },
  F4: { py: "Zhongfeng", cat: "Jing-rio", loc: "1 cun anterior ao maléolo medial, medial ao tendão do tibial anterior.", use: "Jing-rio, genital, hérnia." },
  F5: { py: "Ligou", cat: "Luo", loc: "5 cun acima do maléolo medial, no meio da face medial da tíbia.", use: "Luo, leucorreia, prurido, genital." },
  F6: { py: "Zhongdu", cat: "Xi", loc: "7 cun acima do maléolo medial, na face medial da tíbia.", use: "Xi, dismenorreia, hernia." },
  F7: { py: "Xiguan", cat: "—", loc: "1 cun posterior a BP9, na borda posterior da tíbia.", use: "Joelho medial." },
  F8: { py: "Ququan", cat: "He-mar", loc: "Extremidade medial da prega poplítea, joelho fletido, anterior aos semitendíneo/semimembranoso.", use: "Xue do Fígado, joelho, gineco." },
  F9: { py: "Yinbao", cat: "—", loc: "4 cun acima do epicôndilo medial, entre vasto medial e sartório.", use: "Ciclo, urina." },
  F10: { py: "Zuwuli", cat: "—", loc: "3 cun abaixo de E30, no bordo lateral do adutor longo.", use: "Genital, coxa." },
  F11: { py: "Yinlian", cat: "—", loc: "2 cun abaixo de E30, no bordo lateral do adutor longo.", use: "Ciclo, coxa." },
  F12: { py: "Jimai", cat: "—", loc: "2,5 cun lat. ao ponto médio da borda superior do púbis, no sulco inguinal.", use: "Genital.", caut: "Evitar a femoral." },
  F13: { py: "Zhangmen", cat: "Mu do Baço · Hui dos Zang", loc: "Extremidade livre da 11ª costela.", use: "Baço, Fígado, flanco.", caut: "Raso." },
  F14: { py: "Qimen", cat: "Mu do Fígado", loc: "6º espaço intercostal, na linha mamilar.", use: "Fígado, peito, azia.", caut: "Raso. Gravidez: critério." },
  ID1: { py: "Shaoze", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo ulnar da unha do 5º dedo.", use: "Lactação, olho, calor, sangria." },
  ID2: { py: "Qiangu", cat: "Ying-manancial", loc: "Distal à 5ª MCF, lado ulnar, punho cerrado.", use: "Olho, ouvido, dente." },
  ID3: { py: "Houxi", cat: "Shu-arroio · abre o Du", loc: "Proximal à 5ª MCF, lado ulnar, no fim da prega palmar, punho cerrado.", use: "Abre o Du, nuca, coluna, insônia (olho)." },
  ID4: { py: "Wangu", cat: "Yuan", loc: "Entre a base do 5º metacarpo e o triquetral, lado ulnar.", use: "Yuan do ID, punho, dente." },
  ID5: { py: "Yanggu", cat: "Jing-rio", loc: "Depressão entre o estiloide ulnar e o triquetral.", use: "Punho, ouvido, dente." },
  ID6: { py: "Yanglao", cat: "Xi", loc: "Dorso do punho, na depressão radial à cabeça da ulna, palma no peito.", use: "Xi, ombro, lombar, vista (idoso)." },
  ID7: { py: "Zhizheng", cat: "Luo", loc: "5 cun acima do punho, na linha ID5–ID8.", use: "Luo, nuca, dedos." },
  ID8: { py: "Xiaohai", cat: "He-mar", loc: "Sulco entre o olécrano e o epicôndilo medial, cotovelo fletido.", use: "Cotovelo, nervo ulnar, ID." },
  ID9: { py: "Jianzhen", cat: "—", loc: "1 cun acima da extremidade posterior da prega axilar.", use: "Ombro posterior." },
  ID10: { py: "Naoshu", cat: "—", loc: "Diretamente acima de ID9, na extremidade inferior da espinha da escápula.", use: "Ombro, escápula." },
  ID11: { py: "Tianzong", cat: "—", loc: "Fossa infraespinhal, no terço médio da linha da espinha ao ângulo inferior.", use: "Ombro, mama, asma." },
  ID12: { py: "Bingfeng", cat: "—", loc: "Centro da fossa supraespinhal, acima de ID11.", use: "Ombro.", caut: "Raso no ápice." },
  ID13: { py: "Quyuan", cat: "—", loc: "Extremidade medial da fossa supraespinhal.", use: "Ombro, escápula." },
  ID14: { py: "Jianwaishu", cat: "—", loc: "3 cun lat. a VG13 (T1), no bordo da escápula.", use: "Ombro, nuca." },
  ID15: { py: "Jianzhongshu", cat: "—", loc: "2 cun lat. a VG14 (C7).", use: "Nuca, ombro, tosse." },
  ID16: { py: "Tianchuang", cat: "—", loc: "Borda posterior do ECM, posterior a IG18, no nível da laringe.", use: "Ouvido, garganta." },
  ID17: { py: "Tianrong", cat: "—", loc: "Posterior ao ângulo da mandíbula, no bordo anterior do ECM.", use: "Garganta, ouvido." },
  ID18: { py: "Quanliao", cat: "—", loc: "Diretamente abaixo do canto externo do olho, no bordo inferior do zigoma.", use: "Face, dente, paralisia." },
  ID19: { py: "Tinggong", cat: "—", loc: "Entre o trago e a ATM, com a boca aberta.", use: "Ouvido, zumbido, ATM." },
  IG1: { py: "Shangyang", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo radial da unha do indicador.", use: "Dor de garganta, calor, dente, sangria." },
  IG2: { py: "Erjian", cat: "Ying-manancial", loc: "Distal à 2ª articulação MCF do indicador, lado radial, punho cerrado.", use: "Dor de dente, garganta, calor." },
  IG3: { py: "Sanjian", cat: "Shu-arroio", loc: "Proximal à 2ª cabeça do metacarpo, lado radial, punho cerrado.", use: "Olhos, dente, garganta, diarreia." },
  IG4: { py: "Hegu", cat: "Yuan", loc: "Meio do 2º metacarpo, no lado radial, no ventre do 1º interósseo.", use: "Dor, face, exterior, Quatro Portas com F3.", caut: "Não na gravidez." },
  IG5: { py: "Yangxi", cat: "Jing-rio", loc: "Prega dorsal do punho, entre os tendões de extensor longo e curto do polegar.", use: "Punho, dente, olho, De Quervain." },
  IG6: { py: "Pianli", cat: "Luo", loc: "3 cun acima de IG5, na linha IG5–IG11.", use: "Ouvido, zumbido, Luo do IG." },
  IG7: { py: "Wenliu", cat: "Xi", loc: "5 cun acima de IG5, na linha IG5–IG11.", use: "Dor aguda no antebraço, boca, face." },
  IG8: { py: "Xialian", cat: "—", loc: "4 cun abaixo de IG11, na linha IG5–IG11.", use: "Cotovelo, braço, cabeça." },
  IG9: { py: "Shanglian", cat: "—", loc: "3 cun abaixo de IG11.", use: "Ombro, braço, hemiparesia." },
  IG10: { py: "Shousanli", cat: "—", loc: "2 cun abaixo de IG11, no Yangming do braço.", use: "Dor no braço, ombro, dente, hemiparesia." },
  IG11: { py: "Quchi", cat: "He-mar", loc: "Prega cubital, meio entre o epicôndilo lateral e o tendão do bíceps, cotovelo fletido.", use: "Calor, pele, imunidade, cotovelo." },
  IG12: { py: "Zhouliao", cat: "—", loc: "1 cun acima de IG11, na borda do úmero.", use: "Cotovelo, braço." },
  IG13: { py: "Shouwuli", cat: "—", loc: "3 cun acima de IG11, na linha IG11–IG15.", use: "Braço, cotovelo.", caut: "Cuidado com o nervo radial." },
  IG14: { py: "Binao", cat: "—", loc: "Lateral do braço, inserção do deltoide, na linha IG11–IG15.", use: "Ombro, braço, olho." },
  IG15: { py: "Jianyu", cat: "—", loc: "Depressão ântero-inferior do acrômio, braço em abdução.", use: "Ombro congelado, bursite.", caut: "Não fundo rumo ao ápice pulmonar." },
  IG16: { py: "Jugu", cat: "—", loc: "Depressão entre o acrômio e a espinha da escápula.", use: "Ombro, nuca." },
  IG17: { py: "Tianding", cat: "—", loc: "Lateral do pescoço, 1 cun abaixo de IG18, no bordo posterior do ECM.", use: "Garganta, voz.", caut: "Cuidado com o feixe carotídeo." },
  IG18: { py: "Futu", cat: "—", loc: "Nível da ponta da laringe, entre as duas cabeças do ECM.", use: "Garganta, tosse, voz.", caut: "Cuidado com a carótida." },
  IG19: { py: "Kouheliao", cat: "—", loc: "Abaixo da borda lateral da narina, 0,5 cun.", use: "Nariz, rinite, paralisia facial." },
  IG20: { py: "Yingxiang", cat: "—", loc: "No sulco nasolabial, ao lado da asa do nariz.", use: "Nariz, sinusite, paralisia facial." },
  P1: { py: "Zhongfu", cat: "Mu do Pulmão", loc: "1º espaço intercostal, 6 cun lat. à linha média, abaixo da clavícula.", use: "Tosse, asma, plenitude no peito, ombro.", caut: "Tórax: raso — risco de pneumotórax." },
  P2: { py: "Yunmen", cat: "—", loc: "Abaixo da extremidade acromial da clavícula, 6 cun lat., na depressão.", use: "Tosse, asma, dor no ombro e peito.", caut: "Tórax: raso." },
  P3: { py: "Tianfu", cat: "—", loc: "Face ântero-medial do braço, 3 cun abaixo da prega axilar, no bíceps.", use: "Asma, epistaxe, dor no braço." },
  P4: { py: "Xiabai", cat: "—", loc: "Face ântero-medial do braço, 4 cun abaixo da prega axilar.", use: "Tosse, dor no peito e no braço." },
  P5: { py: "Chize", cat: "He-mar", loc: "Prega cubital, no lado radial do tendão do bíceps.", use: "Tosse, asma, calor no Pulmão, cotovelo." },
  P6: { py: "Kongzui", cat: "Xi", loc: "Palma do antebraço, 7 cun acima da prega do punho, na linha P5–P9.", use: "Tosse aguda, hemoptise, asma." },
  P7: { py: "Lieque", cat: "Luo · abre o Ren", loc: "1,5 cun acima da prega do punho, na styloide do rádio, na tabaqueira.", use: "Exterior, nuca, tosse, abre o Ren com R6.", caut: "Superficial." },
  P8: { py: "Jingqu", cat: "Jing-rio", loc: "1 cun acima da prega do punho, no lado radial da artéria radial.", use: "Tosse, asma, dor no peito.", caut: "Evitar a artéria." },
  P9: { py: "Taiyuan", cat: "Yuan · Hui dos vasos", loc: "Prega do punho, no lado radial da artéria radial, na depressão.", use: "Tosse, asma, pulso, Yuan do Pulmão.", caut: "Evitar a artéria radial." },
  P10: { py: "Yuji", cat: "Ying-manancial", loc: "Meio do 1º metacarpo, na eminência tenar, na palma.", use: "Calor na garganta, tosse, afonia." },
  P11: { py: "Shaoshang", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo radial da unha do polegar.", use: "Dor de garganta, calor, reanimação, sangria." },
  R1: { py: "Yongquan", cat: "Jing-poço", loc: "Terço anterior da planta, na depressão ao fletir os artelhos.", use: "Yang que sobe, Shen, insônia, reanimação.", caut: "Doloroso — avisar." },
  R2: { py: "Rangu", cat: "Ying-manancial", loc: "Borda inferior do navicular, na junção pele vermelha/branca.", use: "Calor vazio, garganta, dismenorreia." },
  R3: { py: "Taixi", cat: "Yuan · Shu-arroio", loc: "Meio entre o maléolo medial e o tendão de Aquiles.", use: "Yin e Jing do Rim, lombar, ouvido, asma de fundo." },
  R4: { py: "Dazhong", cat: "Luo", loc: "0,5 cun abaixo e ligeiramente posterior a R3, no calcâneo.", use: "Luo, calcanhar." },
  R5: { py: "Shuiquan", cat: "Xi", loc: "1 cun abaixo de R3.", use: "Xi, ciclo, urina." },
  R6: { py: "Zhaohai", cat: "Abre o Yin Qiao", loc: "1 cun abaixo do maléolo medial, na depressão.", use: "Yin Qiao, garganta, insônia, Yin." },
  R7: { py: "Fuliu", cat: "Jing-rio", loc: "2 cun acima de R3, borda anterior do Aquiles.", use: "Edema, suor, Jing-rio do Rim." },
  R8: { py: "Jiaoxin", cat: "Xi do Yin Qiao", loc: "2 cun acima de R3, 0,5 cun anterior a R7, borda posterior da tíbia.", use: "Yin Qiao, ciclo, útero." },
  R9: { py: "Zhubin", cat: "Xi do Yin Wei", loc: "5 cun acima de R3, na linha R3–R10.", use: "Yin Wei, panturrilha, Shen." },
  R10: { py: "Yingu", cat: "He-mar", loc: "Lado medial da prega poplítea, entre os tendões do semitendíneo e semimembranoso.", use: "Urina, joelho, jiao inferior." },
  R11: { py: "Henggu", cat: "Chong", loc: "5 cun abaixo do umbigo, 0,5 cun lat. (nível do púbis).", use: "Chong, urina, genital.", caut: "Gravidez: não." },
  R12: { py: "Dahe", cat: "Chong", loc: "4 cun abaixo do umbigo, 0,5 cun lat.", use: "Jing, útero.", caut: "Gravidez: não." },
  R13: { py: "Qixue", cat: "Chong", loc: "3 cun abaixo do umbigo, 0,5 cun lat.", use: "Chong, ciclo.", caut: "Gravidez: não." },
  R14: { py: "Siman", cat: "Chong", loc: "2 cun abaixo do umbigo, 0,5 cun lat.", use: "Chong, estase no jiao inferior.", caut: "Gravidez: não." },
  R15: { py: "Zhongzhu", cat: "—", loc: "1 cun abaixo do umbigo, 0,5 cun lat.", use: "Intestino, ciclo." },
  R16: { py: "Huangshu", cat: "—", loc: "0,5 cun lat. ao umbigo.", use: "Jiao médio, Huang." },
  R17: { py: "Shangqu", cat: "—", loc: "2 cun acima do umbigo, 0,5 cun lat.", use: "Estômago, intestino." },
  R18: { py: "Shiguan", cat: "—", loc: "3 cun acima do umbigo, 0,5 cun lat.", use: "Estômago, vômito." },
  R19: { py: "Yindu", cat: "—", loc: "4 cun acima do umbigo, 0,5 cun lat.", use: "Estômago." },
  R20: { py: "Futonggu", cat: "—", loc: "5 cun acima do umbigo, 0,5 cun lat.", use: "Estômago, tosse." },
  R21: { py: "Youmen", cat: "—", loc: "6 cun acima do umbigo, 0,5 cun lat.", use: "Estômago, Qi rebelde.", caut: "Não fundo." },
  R22: { py: "Bulang", cat: "—", loc: "5º espaço intercostal, 2 cun lat.", use: "Tosse, peito.", caut: "Raso." },
  R23: { py: "Shenfeng", cat: "—", loc: "4º espaço intercostal, 2 cun lat.", use: "Tosse, mama.", caut: "Raso." },
  R24: { py: "Lingxu", cat: "—", loc: "3º espaço intercostal, 2 cun lat.", use: "Tosse, peito.", caut: "Raso." },
  R25: { py: "Shencang", cat: "—", loc: "2º espaço intercostal, 2 cun lat.", use: "Asma, peito.", caut: "Raso." },
  R26: { py: "Yuzhong", cat: "—", loc: "1º espaço intercostal, 2 cun lat.", use: "Asma, peito.", caut: "Raso." },
  R27: { py: "Shufu", cat: "—", loc: "Borda inferior da clavícula, 2 cun lat.", use: "Asma, tosse.", caut: "Raso." },
  TA1: { py: "Guanchong", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo ulnar da unha do 4º dedo.", use: "Calor, ouvido, garganta, sangria." },
  TA2: { py: "Yemen", cat: "Ying-manancial", loc: "Entre 4º e 5º dedos, 0,5 cun proximal à membrana.", use: "Ouvido, cefaleia." },
  TA3: { py: "Zhongzhu", cat: "Shu-arroio", loc: "Dorso da mão, entre 4º e 5º metacarpos, proximal à MCF.", use: "Ouvido, zumbido, dedos." },
  TA4: { py: "Yangchi", cat: "Yuan", loc: "Prega dorsal do punho, no lado ulnar do extensor dos dedos.", use: "Yuan do TA, punho." },
  TA5: { py: "Waiguan", cat: "Luo · abre o Yang Wei", loc: "2 cun acima da prega do punho, entre rádio e ulna.", use: "Yang Wei, Shaoyang, ouvido, exterior, cefaleia." },
  TA6: { py: "Zhigou", cat: "Jing-rio", loc: "3 cun acima da prega do punho, entre rádio e ulna.", use: "Constipação, flanco, Shaoyang." },
  TA7: { py: "Huizong", cat: "Xi", loc: "3 cun acima do punho, 1 dedo ulnar a TA6, no lado da ulna.", use: "Xi, ouvido." },
  TA8: { py: "Sanyangluo", cat: "—", loc: "4 cun acima do punho, entre rádio e ulna.", use: "Afasia, braço, dente." },
  TA9: { py: "Sidu", cat: "—", loc: "5 cun abaixo do olécrano, entre rádio e ulna.", use: "Ouvido, garganta, braço." },
  TA10: { py: "Tianjing", cat: "He-mar", loc: "1 cun acima do olécrano, cotovelo fletido.", use: "He, calor, cotovelo." },
  TA11: { py: "Qinglengyuan", cat: "—", loc: "1 cun acima de TA10.", use: "Ombro, braço." },
  TA12: { py: "Xiaoluo", cat: "—", loc: "Meio da linha TA11–TA13.", use: "Pescoço, braço." },
  TA13: { py: "Naohui", cat: "—", loc: "Na inserção posterior do deltoide, na linha TA10–TA14.", use: "Ombro." },
  TA14: { py: "Jianliao", cat: "—", loc: "Depressão póstero-inferior do acrômio, braço em abdução (fossa posterior).", use: "Ombro posterior." },
  TA15: { py: "Tianliao", cat: "—", loc: "Meio entre VG14 e a extremidade da espinha da escápula, no ângulo superior.", use: "Ombro, trapézio." },
  TA16: { py: "Tianyou", cat: "—", loc: "Posterior ao ECM, posterior e inferior a ID17, no nível do ângulo da mandíbula.", use: "Pescoço, ouvido." },
  TA17: { py: "Yifeng", cat: "—", loc: "Posterior ao lóbulo, na depressão entre a mandíbula e o mastoide.", use: "Ouvido, paralisia facial.", caut: "Raso." },
  TA18: { py: "Qimai", cat: "—", loc: "No centro do mastoide, no meio da linha TA17–TA20.", use: "Ouvido." },
  TA19: { py: "Luxi", cat: "—", loc: "Superior a TA18, 1/3 da distância TA17–TA20.", use: "Ouvido, cefaleia." },
  TA20: { py: "Jiaosun", cat: "—", loc: "Diretamente acima do ápice da orelha, na implantação.", use: "Ouvido, dente, gengiva." },
  TA21: { py: "Ermen", cat: "—", loc: "Anterior ao supratrago, na depressão, boca aberta.", use: "Ouvido." },
  TA22: { py: "Erheliao", cat: "—", loc: "Anterior e superior a TA21, no nível da raiz da hélice, no cabelo.", use: "Ouvido, cefaleia." },
  TA23: { py: "Sizhukong", cat: "—", loc: "Na depressão da extremidade lateral da sobrancelha.", use: "Olho, enxaqueca, tic." },
  VB1: { py: "Tongziliao", cat: "—", loc: "0,5 cun lateral ao canto externo do olho.", use: "Olho, enxaqueca, Shaoyang.", caut: "Raso." },
  VB2: { py: "Tinghui", cat: "—", loc: "Anterior ao intertrago, na depressão, boca aberta.", use: "Ouvido, ATM." },
  VB3: { py: "Shangguan", cat: "—", loc: "Superior ao arco zigomático, acima de E7.", use: "Ouvido, dente." },
  VB4: { py: "Hanyan", cat: "—", loc: "No terço superior da linha E8–VB7, dentro do cabelo.", use: "Enxaqueca, tontura." },
  VB5: { py: "Xuanlu", cat: "—", loc: "Meio da linha E8–VB7.", use: "Enxaqueca." },
  VB6: { py: "Xuanli", cat: "—", loc: "Terço inferior da linha E8–VB7.", use: "Enxaqueca, face." },
  VB7: { py: "Qubin", cat: "—", loc: "1 cun anterior a VB8, na implantação, acima da raiz da orelha.", use: "Enxaqueca, dente." },
  VB8: { py: "Shuaigu", cat: "—", loc: "1,5 cun dentro do cabelo, acima do ápice da orelha.", use: "Enxaqueca." },
  VB9: { py: "Tianchong", cat: "—", loc: "0,5 cun posterior a VB8.", use: "Cefaleia, gengiva." },
  VB10: { py: "Fubai", cat: "—", loc: "Posterior e superior ao mastoide, na linha VB9–VB12.", use: "Ouvido, nuca." },
  VB11: { py: "Touqiaoyin", cat: "—", loc: "Posterior ao mastoide, acima de VB12.", use: "Ouvido, cabeça." },
  VB12: { py: "Wangu", cat: "—", loc: "Depressão posterior e inferior ao mastoide.", use: "Nuca, ouvido." },
  VB13: { py: "Benshen", cat: "—", loc: "0,5 cun dentro do cabelo, 3 cun lat. a VG24.", use: "Shen, vento, cefaleia." },
  VB14: { py: "Yangbai", cat: "—", loc: "1 cun acima do meio da sobrancelha, na vertical da pupila.", use: "Olho, paralisia facial, cefaleia frontal." },
  VB15: { py: "Toulinqi", cat: "—", loc: "0,5 cun dentro do cabelo, vertical da pupila.", use: "Olho, nariz, lágrima." },
  VB16: { py: "Muchuang", cat: "—", loc: "1,5 cun posterior a VB15.", use: "Olho, cefaleia." },
  VB17: { py: "Zhengying", cat: "—", loc: "1,5 cun posterior a VB16.", use: "Cefaleia, dente." },
  VB18: { py: "Chengling", cat: "—", loc: "1,5 cun posterior a VB17.", use: "Cefaleia, nariz." },
  VB19: { py: "Naokong", cat: "—", loc: "1,5 cun posterior a VB18, no nível de VG17, na occipital.", use: "Nuca, vento, cérebro." },
  VB20: { py: "Fengchi", cat: "—", loc: "Depressão entre as inserções do ECM e do trapézio, no nível de VG16.", use: "Vento, nuca, olho, enxaqueca.", caut: "Não fundo rumo ao tronco encefálico." },
  VB21: { py: "Jianjing", cat: "—", loc: "Meio entre VG14 e o acrômio, no ponto mais alto do ombro.", use: "Ombro, pescoço, descida do Qi.", caut: "Não na gravidez." },
  VB22: { py: "Yuanye", cat: "—", loc: "3 cun abaixo da axila, no 4º espaço, linha médio-axilar.", use: "Flanco, axila.", caut: "Raso." },
  VB23: { py: "Zhejin", cat: "—", loc: "1 cun anterior a VB22, 4º espaço.", use: "Flanco, asma.", caut: "Raso." },
  VB24: { py: "Riyue", cat: "Mu da VB", loc: "7º espaço intercostal, na linha mamilar.", use: "VB, flanco, amargor.", caut: "Raso." },
  VB25: { py: "Jingmen", cat: "Mu do Rim", loc: "Extremidade livre da 12ª costela.", use: "Rim, lombar, urina." },
  VB26: { py: "Daimai", cat: "Dai Mai", loc: "Meio entre as costelas livres e a crista ilíaca, no nível do umbigo.", use: "Dai Mai, leucorreia, flanco." },
  VB27: { py: "Wushu", cat: "Dai", loc: "Anterior à EIAS, 3 cun abaixo do nível do umbigo.", use: "Dai, hérnia, ciclo." },
  VB28: { py: "Weidao", cat: "Dai", loc: "Anterior e inferior à EIAS, 0,5 cun anterior e inferior a VB27.", use: "Dai, leucorreia." },
  VB29: { py: "Juliao", cat: "—", loc: "Meio entre a EIAS e o trocânter maior.", use: "Quadril, Dai." },
  VB30: { py: "Huantiao", cat: "—", loc: "1/3 lateral da linha trocânter maior — hiato sacral, deitado de lado com o joelho fletido.", use: "Ciático, quadril.", caut: "Profundo, rumo à articulação — não no nervo." },
  VB31: { py: "Fengshi", cat: "—", loc: "Lateral da coxa, onde a ponta do 3º dedo toca, em pé com os braços caídos (7 cun acima da prega poplítea).", use: "Vento, pele, prurido, coxa." },
  VB32: { py: "Zhongdu", cat: "—", loc: "5 cun acima da prega poplítea, entre vasto lateral e bíceps femoral.", use: "Coxa, pele." },
  VB33: { py: "Xiyangguan", cat: "—", loc: "3 cun acima de VB34, na depressão lateral do joelho, acima do epicôndilo.", use: "Joelho lateral." },
  VB34: { py: "Yanglingquan", cat: "He-mar · Hui dos tendões", loc: "Depressão ântero-inferior à cabeça da fíbula.", use: "Tendão, Shaoyang, flanco, joelho." },
  VB35: { py: "Yangjiao", cat: "Xi do Yang Wei", loc: "7 cun acima do maléolo lat., borda posterior da fíbula.", use: "Yang Wei, flanco." },
  VB36: { py: "Waiqiu", cat: "Xi", loc: "7 cun acima do maléolo lat., borda anterior da fíbula.", use: "Xi da VB, pescoço." },
  VB37: { py: "Guangming", cat: "Luo", loc: "5 cun acima do maléolo lat., borda anterior da fíbula.", use: "Luo, olho, perna." },
  VB38: { py: "Yangfu", cat: "Jing-rio", loc: "4 cun acima do maléolo lat., anterior à fíbula.", use: "Jing-rio, axila, flanco." },
  VB39: { py: "Xuanzhong", cat: "Hui da medula", loc: "3 cun acima do maléolo lat., borda anterior da fíbula.", use: "Mar da medula, nuca, hemiparesia." },
  VB40: { py: "Qiuxu", cat: "Yuan", loc: "Anterior e inferior ao maléolo lat., na depressão lateral do tendão do EDL.", use: "Yuan da VB, tornozelo, flanco." },
  VB41: { py: "Zulinqi", cat: "Shu-arroio · abre o Dai", loc: "Depressão distal à junção do 4º e 5º metatarsos, no lado lateral do EDL.", use: "Dai Mai, enxaqueca, ciclo, pé." },
  VB42: { py: "Diwuhui", cat: "—", loc: "Entre 4º e 5º metatarsos, 0,5 cun anterior a VB41.", use: "Pé, flanco, mama." },
  VB43: { py: "Xiaxi", cat: "Ying-manancial", loc: "Entre 4º e 5º artelhos, 0,5 cun proximal à membrana.", use: "Enxaqueca, ouvido, calor da VB." },
  VB44: { py: "Zuqiaoyin", cat: "Jing-poço", loc: "0,1 cun proximal ao ângulo lateral da unha do 4º artelho.", use: "Insônia, flanco, calor, sangria." },
  VC1: { py: "Huiyin", cat: "—", loc: "Centro do períneo, entre ânus e escroto/comissura.", use: "Yin, reanimação, hemorroida.", caut: "Períneo. Não na gravidez." },
  VC2: { py: "Qugu", cat: "—", loc: "Borda superior da sínfise púbica, linha média.", use: "Urina, genital.", caut: "Gravidez: não." },
  VC3: { py: "Zhongji", cat: "Mu da Bexiga", loc: "4 cun abaixo do umbigo, linha média.", use: "Bexiga, útero, urina.", caut: "Gravidez: não." },
  VC4: { py: "Guanyuan", cat: "Mu do ID · mar do Qi", loc: "3 cun abaixo do umbigo.", use: "Jing, útero, Yang, ID.", caut: "Gravidez: não." },
  VC5: { py: "Shimen", cat: "Mu do San Jiao", loc: "2 cun abaixo do umbigo.", use: "San Jiao, edema.", caut: "Gravidez: não." },
  VC6: { py: "Qihai", cat: "Mar do Qi", loc: "1,5 cun abaixo do umbigo.", use: "Qi, fadiga, jiao inferior." },
  VC7: { py: "Yinjiao", cat: "—", loc: "1 cun abaixo do umbigo.", use: "Ciclo, genital." },
  VC8: { py: "Shenque", cat: "—", loc: "Centro do umbigo.", use: "Yang, diarreia, colapso.", caut: "Não puncionar. Moxa só se pele íntegra." },
  VC9: { py: "Shuifen", cat: "—", loc: "1 cun acima do umbigo.", use: "Água, edema.", caut: "Raso." },
  VC10: { py: "Xiawan", cat: "—", loc: "2 cun acima do umbigo.", use: "Estômago, alimento parado." },
  VC11: { py: "Jianli", cat: "—", loc: "3 cun acima do umbigo.", use: "Estômago, edema." },
  VC12: { py: "Zhongwan", cat: "Mu do Estômago · Hui dos Fu", loc: "4 cun acima do umbigo.", use: "Jiao médio, gastrite, náusea.", caut: "Raso." },
  VC13: { py: "Shangwan", cat: "—", loc: "5 cun acima do umbigo.", use: "Estômago, vômito." },
  VC14: { py: "Juque", cat: "Mu do Coração", loc: "6 cun acima do umbigo (2 cun abaixo do ângulo esternal).", use: "Coração, palpitação, Shen.", caut: "Raso — fígado esquerdo." },
  VC15: { py: "Jiuwei", cat: "Luo do Ren", loc: "7 cun acima do umbigo, 1 cun abaixo do apêndice xifoide.", use: "Luo, peito, Shen.", caut: "Raso." },
  VC16: { py: "Zhongting", cat: "—", loc: "No 5º espaço, na linha média, no ângulo esternal.", use: "Peito, náusea.", caut: "Raso." },
  VC17: { py: "Danzhong", cat: "Mu do CS · Hui do Qi", loc: "4º espaço intercostal, linha média, no nível dos mamilos.", use: "Qi do tórax, asma, leite, CS.", caut: "Raso." },
  VC18: { py: "Yutang", cat: "—", loc: "3º espaço, linha média.", use: "Tosse, peito.", caut: "Raso." },
  VC19: { py: "Zigong", cat: "—", loc: "2º espaço, linha média. Não confundir com extra Zigong.", use: "Tosse, peito.", caut: "Raso." },
  VC20: { py: "Huagai", cat: "—", loc: "1º espaço, linha média.", use: "Tosse, asma.", caut: "Raso." },
  VC21: { py: "Xuanji", cat: "—", loc: "Centro do manúbrio.", use: "Tosse, garganta.", caut: "Raso." },
  VC22: { py: "Tiantu", cat: "—", loc: "Centro da fossa supraesternal.", use: "Tosse, asma, Qi rebelde, garganta.", caut: "Primeiro raso, depois atrás do esterno com critério." },
  VC23: { py: "Lianquan", cat: "—", loc: "Acima da borda superior do hioide, na depressão.", use: "Língua, afasia, saliva." },
  VC24: { py: "Chengjiang", cat: "—", loc: "Depressão no centro do sulco mentolabial.", use: "Paralisia facial, boca, sialorreia." },
  VG1: { py: "Changqiang", cat: "Du Mai", loc: "Meio entre o cóccix e o ânus.", use: "Hemorroida, ânus, abre o Du.", caut: "Períneo." },
  VG2: { py: "Yaoshu", cat: "Du Mai", loc: "Hiato sacral, na linha média.", use: "Lombar, hemorroida." },
  VG3: { py: "Yaoyangguan", cat: "Du Mai", loc: "Abaixo de L4.", use: "Lombar baixa, membros inferiores." },
  VG4: { py: "Mingmen", cat: "Du Mai", loc: "Abaixo de L2.", use: "Yang do Rim, lombar, Mingmen.", caut: "Não em calor vazio." },
  VG5: { py: "Xuanshu", cat: "Du Mai", loc: "Abaixo de L1.", use: "Lombar, intestino." },
  VG6: { py: "Jizhong", cat: "Du Mai", loc: "Abaixo de T11.", use: "Baço, hemorragia, epilepsia (apoio)." },
  VG7: { py: "Zhongshu", cat: "Du Mai", loc: "Abaixo de T10.", use: "Estômago, lombar." },
  VG8: { py: "Jinsuo", cat: "Du Mai", loc: "Abaixo de T9.", use: "Fígado, espasmo, tendão." },
  VG9: { py: "Zhiyang", cat: "Du Mai", loc: "Abaixo de T7.", use: "Peito, icterícia (clássico), Yang." },
  VG10: { py: "Lingtai", cat: "Du Mai", loc: "Abaixo de T6.", use: "Asma, furúnculo (clássico)." },
  VG11: { py: "Shendao", cat: "Du Mai", loc: "Abaixo de T5.", use: "Shen, palpitação." },
  VG12: { py: "Shenzhu", cat: "Du Mai", loc: "Abaixo de T3.", use: "Pulmão, vento, asma." },
  VG13: { py: "Taodao", cat: "Du Mai", loc: "Abaixo de T1.", use: "Vento, malaria (clássico), nuca." },
  VG14: { py: "Dazhui", cat: "Du Mai", loc: "Abaixo de C7.", use: "Encontro de todos os Yang, vento, calor, imunidade." },
  VG15: { py: "Yamen", cat: "Du Mai", loc: "0,5 cun acima da implantação posterior, abaixo de C1.", use: "Afasia, vento.", caut: "Não fundo — medula." },
  VG16: { py: "Fengfu", cat: "Du Mai", loc: "1 cun acima da implantação posterior, na depressão abaixo da occipital.", use: "Vento, cérebro, nuca.", caut: "Não fundo rumo ao tronco." },
  VG17: { py: "Naohu", cat: "Du Mai", loc: "1,5 cun acima de VG16, borda superior da occipital.", use: "Cérebro, nuca." },
  VG18: { py: "Qiangjian", cat: "Du Mai", loc: "1,5 cun acima de VG17.", use: "Cefaleia, vento." },
  VG19: { py: "Houding", cat: "Du Mai", loc: "1,5 cun acima de VG18.", use: "Vértice, vento." },
  VG20: { py: "Baihui", cat: "Du Mai", loc: "Vértice, meio da linha dos ápices das orelhas.", use: "Yang, Shen, prolapso, tontura. Direção da agulha muda o sentido do Qi." },
  VG21: { py: "Qianding", cat: "Du Mai", loc: "1,5 cun anterior a VG20.", use: "Vértice, vento." },
  VG22: { py: "Xinhui", cat: "Du Mai", loc: "2 cun posterior à linha capilar anterior (3 cun anterior a VG20).", use: "Cabeça, nariz." },
  VG23: { py: "Shangxing", cat: "Du Mai", loc: "1 cun posterior à linha capilar anterior.", use: "Nariz, sinusite, olho." },
  VG24: { py: "Shenting", cat: "Du Mai", loc: "0,5 cun posterior à linha capilar anterior, na linha média.", use: "Shen, rinite, cefaleia frontal." },
  VG25: { py: "Suliao", cat: "Du Mai", loc: "Ponta do nariz.", use: "Nariz, reanimação, rosácea (apoio)." },
  VG26: { py: "Shuigou", cat: "Du Mai", loc: "Terço superior do filtro, abaixo do septo.", use: "Reanimação, lombar aguda, face." },
  VG27: { py: "Duiduan", cat: "Du Mai", loc: "Tubérculo do lábio superior, na linha média.", use: "Boca, lábio, reanimação." },
  VG28: { py: "Yinjiao", cat: "Du Mai", loc: "Freio do lábio superior, no vestíbulo.", use: "Gengiva, hemorroida (clássico)." },
};

export const EXTRA_SPECS: Record<string, PointSpec> = {
  Yintang: { py: "Yintang", cat: "Extra", loc: "Entre as sobrancelhas, na linha média.", use: "Shen, rinite, cefaleia frontal." },
  Sishencong: { py: "Sishencong", cat: "Extra", loc: "1 cun anterior, posterior e laterais a VG20, em cruz.", use: "Insônia, memória, vento." },
  Anmian: { py: "Anmian", cat: "Extra", loc: "Meio entre VB20 e TA17.", use: "Insônia rebelde." },
  Taiyang: { py: "Taiyang", cat: "Extra", loc: "Fossa temporal, 1 cun posterior ao ponto médio da linha canto externo–extremidade da sobrancelha.", use: "Enxaqueca temporal." },
  Bitong: { py: "Bitong", cat: "Extra", loc: "Ponto mais alto do sulco nasolabial.", use: "Nariz fechado, sinusite." },
  Dingchuan: { py: "Dingchuan", cat: "Extra", loc: "0,5 cun lat. a VG14.", use: "Asma, chiado." },
  Huatojiaji: { py: "Huatuojiaji", cat: "Extra", loc: "0,5 cun lat. aos processos T1–L5.", use: "Segmentar, coluna, órgão do nível." },
  Xiyan: { py: "Xiyan", cat: "Extra", loc: "Olhos do joelho: E35 (lat.) e o olho medial.", use: "Joelho.", caut: "Não em articulação infectada." },
  Heding: { py: "Heding", cat: "Extra", loc: "Depressão acima do centro da borda superior da patela.", use: "Joelho." },
  Jianqian: { py: "Jianqian", cat: "Extra", loc: "Meio entre a extremidade anterior da prega axilar e IG15.", use: "Ombro anterior." },
  Zigong: { py: "Zigong", cat: "Extra", loc: "3 cun lat. a VC3.", use: "Útero, ciclo.", caut: "Não na gravidez." },
  Luozhen: { py: "Luozhen", cat: "Extra", loc: "Dorso da mão, entre 2º e 3º metacarpos, 0,5 cun proximal à MCF.", use: "Torcicolo." },
  Shiqizhui: { py: "Shiqizhui", cat: "Extra", loc: "Abaixo de L5, na linha média.", use: "Lombar baixa." },
  Jingbailao: { py: "Jingbailao", cat: "Extra", loc: "2 cun acima de VG14 e 1 cun lat.", use: "Nuca, tosse." },
  Qianzheng: { py: "Qianzheng", cat: "Extra", loc: "0,5–1 cun anterior ao lóbulo.", use: "Paralisia facial." },
  Weiguanxiashu: { py: "Weiguanxiashu", cat: "Extra", loc: "1,5 cun lat. ao processo T8.", use: "Pâncreas, sede, diabetes (apoio)." },
  Yuyao: { py: "Yuyao", cat: "Extra", loc: "Meio da sobrancelha, vertical da pupila.", use: "Olho, pálpebra." },
  Baxie: { py: "Baxie", cat: "Extra", loc: "Membranas interdigitais do dorso da mão, punho cerrado.", use: "Dedos, calor." },
  Bafeng: { py: "Bafeng", cat: "Extra", loc: "Membranas interdigitais do dorso do pé.", use: "Artelhos, calor." },
};

