/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FichaRouteImport } from './routes/ficha'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as MassagemRouteImport } from './routes/massagem'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as OrelhaRouteImport } from './routes/orelha'
import { Route as ProtocolosRouteImport } from './routes/protocolos'
import { Route as VasosRouteImport } from './routes/vasos'
import { Route as VetRouteImport } from './routes/vet'
import { Route as YnsaRouteImport } from './routes/ynsa'
import { Route as MeridianoIdRouteImport } from './routes/meridiano.$id'
import { Route as PontoCodeRouteImport } from './routes/ponto.$code'
import { Route as ProtocoloSlugRouteImport } from './routes/protocolo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaRoute = FichaRouteImport.update({
  id: '/ficha',
  path: '/ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const MassagemRoute = MassagemRouteImport.update({
  id: '/massagem',
  path: '/massagem',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrelhaRoute = OrelhaRouteImport.update({
  id: '/orelha',
  path: '/orelha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosRoute = ProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => rootRouteImport,
} as any)
const VasosRoute = VasosRouteImport.update({
  id: '/vasos',
  path: '/vasos',
  getParentRoute: () => rootRouteImport,
} as any)
const VetRoute = VetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => rootRouteImport,
} as any)
const YnsaRoute = YnsaRouteImport.update({
  id: '/ynsa',
  path: '/ynsa',
  getParentRoute: () => rootRouteImport,
} as any)
const MeridianoIdRoute = MeridianoIdRouteImport.update({
  id: '/meridiano/$id',
  path: '/meridiano/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoCodeRoute = PontoCodeRouteImport.update({
  id: '/ponto/$code',
  path: '/ponto/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloSlugRoute = ProtocoloSlugRouteImport.update({
  id: '/protocolo/$slug',
  path: '/protocolo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/consulta': typeof ConsultaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/documentos': typeof DocumentosRoute
  '/ficha': typeof FichaRoute
  '/inicio': typeof InicioRoute
  '/massagem': typeof MassagemRoute
  '/metodo': typeof MetodoRoute
  '/orelha': typeof OrelhaRoute
  '/protocolos': typeof ProtocolosRoute
  '/vasos': typeof VasosRoute
  '/vet': typeof VetRoute
  '/ynsa': typeof YnsaRoute
  '/meridiano/$id': typeof MeridianoIdRoute
  '/ponto/$code': typeof PontoCodeRoute
  '/protocolo/$slug': typeof ProtocoloSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/consulta': typeof ConsultaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/documentos': typeof DocumentosRoute
  '/ficha': typeof FichaRoute
  '/inicio': typeof InicioRoute
  '/massagem': typeof MassagemRoute
  '/metodo': typeof MetodoRoute
  '/orelha': typeof OrelhaRoute
  '/protocolos': typeof ProtocolosRoute
  '/vasos': typeof VasosRoute
  '/vet': typeof VetRoute
  '/ynsa': typeof YnsaRoute
  '/meridiano/$id': typeof MeridianoIdRoute
  '/ponto/$code': typeof PontoCodeRoute
  '/protocolo/$slug': typeof ProtocoloSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/consulta': typeof ConsultaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/documentos': typeof DocumentosRoute
  '/ficha': typeof FichaRoute
  '/inicio': typeof InicioRoute
  '/massagem': typeof MassagemRoute
  '/metodo': typeof MetodoRoute
  '/orelha': typeof OrelhaRoute
  '/protocolos': typeof ProtocolosRoute
  '/vasos': typeof VasosRoute
  '/vet': typeof VetRoute
  '/ynsa': typeof YnsaRoute
  '/meridiano/$id': typeof MeridianoIdRoute
  '/ponto/$code': typeof PontoCodeRoute
  '/protocolo/$slug': typeof ProtocoloSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/consulta'
    | '/diagnostico'
    | '/documentos'
    | '/ficha'
    | '/inicio'
    | '/massagem'
    | '/metodo'
    | '/orelha'
    | '/protocolos'
    | '/vasos'
    | '/vet'
    | '/ynsa'
    | '/meridiano/$id'
    | '/ponto/$code'
    | '/protocolo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/consulta'
    | '/diagnostico'
    | '/documentos'
    | '/ficha'
    | '/inicio'
    | '/massagem'
    | '/metodo'
    | '/orelha'
    | '/protocolos'
    | '/vasos'
    | '/vet'
    | '/ynsa'
    | '/meridiano/$id'
    | '/ponto/$code'
    | '/protocolo/$slug'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/consulta'
    | '/diagnostico'
    | '/documentos'
    | '/ficha'
    | '/inicio'
    | '/massagem'
    | '/metodo'
    | '/orelha'
    | '/protocolos'
    | '/vasos'
    | '/vet'
    | '/ynsa'
    | '/meridiano/$id'
    | '/ponto/$code'
    | '/protocolo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  ConsultaRoute: typeof ConsultaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DocumentosRoute: typeof DocumentosRoute
  FichaRoute: typeof FichaRoute
  InicioRoute: typeof InicioRoute
  MassagemRoute: typeof MassagemRoute
  MetodoRoute: typeof MetodoRoute
  OrelhaRoute: typeof OrelhaRoute
  ProtocolosRoute: typeof ProtocolosRoute
  VasosRoute: typeof VasosRoute
  VetRoute: typeof VetRoute
  YnsaRoute: typeof YnsaRoute
  MeridianoIdRoute: typeof MeridianoIdRoute
  PontoCodeRoute: typeof PontoCodeRoute
  ProtocoloSlugRoute: typeof ProtocoloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha': {
      id: '/ficha'
      path: '/ficha'
      fullPath: '/ficha'
      preLoaderRoute: typeof FichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/massagem': {
      id: '/massagem'
      path: '/massagem'
      fullPath: '/massagem'
      preLoaderRoute: typeof MassagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orelha': {
      id: '/orelha'
      path: '/orelha'
      fullPath: '/orelha'
      preLoaderRoute: typeof OrelhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos': {
      id: '/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof ProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vasos': {
      id: '/vasos'
      path: '/vasos'
      fullPath: '/vasos'
      preLoaderRoute: typeof VasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet': {
      id: '/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof VetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ynsa': {
      id: '/ynsa'
      path: '/ynsa'
      fullPath: '/ynsa'
      preLoaderRoute: typeof YnsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meridiano/$id': {
      id: '/meridiano/$id'
      path: '/meridiano/$id'
      fullPath: '/meridiano/$id'
      preLoaderRoute: typeof MeridianoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/$code': {
      id: '/ponto/$code'
      path: '/ponto/$code'
      fullPath: '/ponto/$code'
      preLoaderRoute: typeof PontoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo/$slug': {
      id: '/protocolo/$slug'
      path: '/protocolo/$slug'
      fullPath: '/protocolo/$slug'
      preLoaderRoute: typeof ProtocoloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  ConsultaRoute: ConsultaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DocumentosRoute: DocumentosRoute,
  FichaRoute: FichaRoute,
  InicioRoute: InicioRoute,
  MassagemRoute: MassagemRoute,
  MetodoRoute: MetodoRoute,
  OrelhaRoute: OrelhaRoute,
  ProtocolosRoute: ProtocolosRoute,
  VasosRoute: VasosRoute,
  VetRoute: VetRoute,
  YnsaRoute: YnsaRoute,
  MeridianoIdRoute: MeridianoIdRoute,
  PontoCodeRoute: PontoCodeRoute,
  ProtocoloSlugRoute: ProtocoloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
